// data/sources/react-native/alert/Alert.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Alert component for displaying important messages with variants
 */

import * as React from 'react';
import { View, Text, ViewProps, TextProps } from 'react-native';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';

const alertVariants = cva(
  'relative w-full rounded-lg border p-4',
  {
    variants: {
      variant: {
        default: 'bg-background text-foreground',
        destructive: 'border-destructive/50 text-destructive bg-destructive/10',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
);

export interface AlertProps extends ViewProps, VariantProps<typeof alertVariants> {
  /** Visual style variant for the alert */
  variant?: 'default' | 'destructive';
  /** CSS class names for the alert container */
  className?: string;
  /** Alert content */
  children?: React.ReactNode;
}

export type AlertTitleProps = TextProps;
export type AlertDescriptionProps = TextProps;

const Alert = React.forwardRef<View, AlertProps>(
  ({ className, variant, ...props }, ref) => {
    return (
      <View
        ref={ref}
        role="alert"
        className={cn(alertVariants({ variant }), className)}
        {...props}
      />
    );
  }
);

Alert.displayName = 'Alert';

const AlertTitle = React.forwardRef<Text, TextProps>(
  ({ className, ...props }, ref) => {
    return (
      <Text
        ref={ref}
        className={cn('mb-1 font-medium leading-none tracking-tight', className)}
        {...props}
      />
    );
  }
);

AlertTitle.displayName = 'AlertTitle';

const AlertDescription = React.forwardRef<Text, TextProps>(
  ({ className, ...props }, ref) => {
    return (
      <Text
        ref={ref}
        className={cn('text-sm opacity-90', className)}
        {...props}
      />
    );
  }
);

AlertDescription.displayName = 'AlertDescription';

export { Alert, AlertTitle, AlertDescription, alertVariants };

// data/sources/angular/alert/alert.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Alert messages with 4 variants for different contexts
 */

import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { type AlertVariants, alertVariants } from './variants';
import { cn } from '../../lib/utils';

@Component({
  selector: 'ui-alert',
  standalone: true,
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertComponent {
  @Input() variant: AlertVariants['variant'] = 'default';
  @Input() class?: string;

  @HostBinding('class')
  get hostClasses(): string {
    return cn(alertVariants({ variant: this.variant }), this.class);
  }
}

@Component({
  selector: 'ui-alert-title',
  standalone: true,
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertTitleComponent {
  @Input() class?: string;

  @HostBinding('class')
  get hostClasses(): string {
    return cn('mb-1 font-medium leading-none tracking-tight', this.class);
  }
}

@Component({
  selector: 'ui-alert-description',
  standalone: true,
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDescriptionComponent {
  @Input() class?: string;

  @HostBinding('class')
  get hostClasses(): string {
    return cn('text-sm [&_p]:leading-relaxed', this.class);
  }
}
