// data/sources/vue/toolbar/Toolbar.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Toolbar component - Group of controls with Radix Toolbar primitive
-->
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { ToolbarRoot } from 'radix-vue'

defineOptions({
  name: 'UiToolbar',
})

interface Props {
  class?: string
}

const props = defineProps<Props>()
</script>

<template>
  <ToolbarRoot
    :class="
      cn(
        'flex w-full min-w-max items-center gap-1 rounded-md bg-background p-1',
        props.class
      )
    "
  >
    <slot />
  </ToolbarRoot>
</template>

// data/sources/angular/toolbar/toolbar.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Toolbar container for grouping action buttons
 */

import { Component, Input } from '@angular/core'
import { cn } from '../../lib/utils'

@Component({
  selector: 'ui-toolbar',
  standalone: true,
  template: `
    <div [class]="className">
      <ng-content />
    </div>
  `,
})
export class ToolbarComponent {
  @Input() class?: string

  get className(): string {
    return cn(
      'flex w-full min-w-max items-center gap-1 rounded-md bg-background p-1',
      this.class
    )
  }
}
