// data/sources/react/donut-chart/DonutChart.tsx
import React, { useMemo } from 'react'
import ReactECharts from 'echarts-for-react'
import type { EChartsOption } from 'echarts'
import { cn } from '@/lib/utils'
import type { DonutChartProps } from './types'
import { getDefaultColors, formatNumber } from './utils'

function getNumericValue(value: unknown): number {
  if (typeof value === 'number') {
    return value
  }

  if (typeof value === 'string') {
    const parsedValue = Number(value)
    return Number.isFinite(parsedValue) ? parsedValue : 0
  }

  if (Array.isArray(value) && typeof value[0] === 'number') {
    return value[0]
  }

  return 0
}

type ChartFormatterParams = {
  name?: string
  value?: unknown
}

export interface DonutChartComponentProps extends DonutChartProps {
  className?: string
}

export const DonutChart = React.forwardRef<ReactECharts, DonutChartComponentProps>(
  (props, ref) => {
    const {
      data,
      height = 300,
      width = '100%',
      theme = 'light',
      legend = true,
      legendPosition = 'right',
      innerRadius = 50,
      outerRadius = 70,
      showPercentage = true,
      labelPosition = 'outside',
      animation = true,
      loading = false,
      emptyText = 'No data available',
      className,
      options = {},
    } = props

    const chartOption = useMemo<EChartsOption | null>(() => {
      if (!data || !data.datasets || data.datasets.length === 0) {
        return null
      }

      const colors = getDefaultColors()
      const dataset = data.datasets[0] // Donut charts typically use first dataset
      const total = dataset.data.reduce((sum, val) => sum + val, 0)

      const pieData = data.labels.map((label, index) => ({
        name: label,
        value: dataset.data[index],
        itemStyle: {
          color: dataset.backgroundColor?.[index] || colors[index % colors.length],
        },
      }))

      return {
        backgroundColor: 'transparent',
        color: colors,
        tooltip: {
          trigger: 'item',
          formatter: (params: ChartFormatterParams) => {
            const value = getNumericValue(params?.value)
            const percent = total > 0 ? ((value / total) * 100).toFixed(1) : '0.0'
            return `${params?.name ?? ''}: ${formatNumber(value)} (${percent}%)`
          },
          backgroundColor: theme === 'dark' ? '#18181b' : '#ffffff',
          borderColor: theme === 'dark' ? '#27272a' : '#e4e4e7',
          textStyle: {
            color: theme === 'dark' ? '#fafafa' : '#0a0a0a',
          },
        },
        legend: legend
          ? {
              orient: legendPosition === 'left' || legendPosition === 'right'
                ? 'vertical'
                : 'horizontal',
              [legendPosition]: legendPosition === 'top' || legendPosition === 'bottom'
                ? 'center'
                : '0',
              [legendPosition === 'top' || legendPosition === 'bottom'
                ? legendPosition
                : 'middle']: '0',
              textStyle: {
                color: theme === 'dark' ? '#fafafa' : '#0a0a0a',
              },
            }
          : undefined,
        series: [
          {
            type: 'pie',
            radius: [`${innerRadius}%`, `${outerRadius}%`],
            center: ['50%', '50%'],
            data: pieData,
            emphasis: {
              itemStyle: {
                shadowBlur: 10,
                shadowOffsetX: 0,
                shadowColor: 'rgba(0, 0, 0, 0.5)',
              },
            },
            label: {
              show: labelPosition !== 'center',
              position: labelPosition === 'inside' ? 'inside' : 'outside',
              formatter: showPercentage
                ? (params: ChartFormatterParams) => {
                    const value = getNumericValue(params?.value)
                    const percent = total > 0 ? ((value / total) * 100).toFixed(1) : '0.0'
                    return `${params?.name ?? ''}\n${percent}%`
                  }
                : '{b}',
              color: theme === 'dark' ? '#fafafa' : '#0a0a0a',
            },
            labelLine: {
              show: labelPosition === 'outside',
            },
          },
        ],
        animation: animation,
        animationDuration: animation ? 1000 : 0,
        ...options,
      } as EChartsOption
    }, [
      data,
      theme,
      legend,
      legendPosition,
      innerRadius,
      outerRadius,
      showPercentage,
      labelPosition,
      animation,
      options,
    ])

    const dimensions = useMemo(() => {
      return {
        height: `${height}px`,
        width: typeof width === 'number' ? `${width}px` : width,
      }
    }, [width, height])

    // Loading state
    if (loading) {
      return (
        <div className={cn('galaxy-donut-chart w-full', className)}>
          <div
            style={{ height: `${height}px` }}
            className="flex items-center justify-center"
          >
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </div>
      )
    }

    // Empty state
    if (!chartOption) {
      return (
        <div className={cn('galaxy-donut-chart w-full', className)}>
          <div
            style={{ height: `${height}px` }}
            className="flex items-center justify-center border border-border rounded-md"
          >
            <p className="text-muted-foreground text-sm">{emptyText}</p>
          </div>
        </div>
      )
    }

    return (
      <div className={cn('galaxy-donut-chart w-full', className)}>
        <ReactECharts
          ref={ref}
          option={chartOption}
          style={dimensions}
          theme={theme}
          showLoading={loading}
          opts={{ renderer: 'canvas' }}
        />
      </div>
    )
  }
)

DonutChart.displayName = 'DonutChart'

// data/sources/vue/donut-chart/donutchart.vue
<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { PieChart } from 'echarts/charts'
import {
  TitleComponent,
  TooltipComponent,
  LegendComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { cn } from '@/lib/utils'
import type { DonutChartProps } from './types'
import { getDefaultColors, formatNumber } from './utils'

defineOptions({
  name: 'UiDonutChart',
})

// Register ECharts components
use([
  PieChart,
  TitleComponent,
  TooltipComponent,
  LegendComponent,
  CanvasRenderer,
])

export interface Props extends DonutChartProps {
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  height: 300,
  width: '100%',
  theme: 'light',
  legend: true,
  legendPosition: 'right',
  animation: true,
  innerRadius: 50,
  outerRadius: 70,
  showPercentage: true,
  labelPosition: 'outside',
  loading: false,
  emptyText: 'No data available',
})

const chartOption = computed(() => {
  if (!props.data || !props.data.datasets || props.data.datasets.length === 0) {
    return null
  }

  const colors = getDefaultColors()
  const dataset = props.data.datasets[0] // Donut charts typically use first dataset
  if (!dataset) return {}

  const total = dataset.data.reduce((sum, val) => sum + val, 0)

  const pieData = props.data.labels.map((label, index) => ({
    name: label,
    value: dataset.data[index],
    itemStyle: {
      color: dataset.backgroundColor?.[index] || colors[index % colors.length],
    },
  }))

  return {
    backgroundColor: 'transparent',
    color: colors,
    tooltip: {
      trigger: 'item',
      formatter: (params: Record<string, unknown>) => {
        const percent = (((params.value as number) / total) * 100).toFixed(1)
        return `${params.name}: ${formatNumber(params.value as number)} (${percent}%)`
      },
      backgroundColor: props.theme === 'dark' ? '#18181b' : '#ffffff',
      borderColor: props.theme === 'dark' ? '#27272a' : '#e4e4e7',
      textStyle: {
        color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
      },
    },
    legend: props.legend
      ? {
          orient: props.legendPosition === 'left' || props.legendPosition === 'right'
            ? 'vertical'
            : 'horizontal',
          [props.legendPosition]: props.legendPosition === 'top' || props.legendPosition === 'bottom'
            ? 'center'
            : '0',
          [props.legendPosition === 'top' || props.legendPosition === 'bottom'
            ? props.legendPosition
            : 'middle']: '0',
          textStyle: {
            color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
          },
        }
      : undefined,
    series: [
      {
        type: 'pie',
        radius: [`${props.innerRadius}%`, `${props.outerRadius}%`],
        center: ['50%', '50%'],
        data: pieData,
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)',
          },
        },
        label: {
          show: props.labelPosition !== 'center',
          position: props.labelPosition === 'inside' ? 'inside' : 'outside',
          formatter: props.showPercentage
            ? (params: Record<string, unknown>) => {
                const percent = (((params.value as number) / total) * 100).toFixed(1)
                return `${params.name}\n${percent}%`
              }
            : '{b}',
          color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
        },
        labelLine: {
          show: props.labelPosition === 'outside',
        },
      },
    ],
  }
})

const dimensions = computed(() => {
  return {
    height: `${props.height}px`,
    width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  }
})
</script>

<template>
  <div :class="cn('galaxy-donut-chart w-full', props.class)">
    <!-- Loading state -->
    <div
      v-if="loading"
      :style="{ height: `${height}px` }"
      class="flex items-center justify-center"
    >
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
    </div>

    <!-- Empty state -->
    <div
      v-else-if="!chartOption"
      :style="{ height: `${height}px` }"
      class="flex items-center justify-center border border-border rounded-md"
    >
      <p class="text-muted-foreground text-sm">{{ emptyText }}</p>
    </div>

    <!-- Chart -->
    <VChart
      v-else
      :option="chartOption"
      :style="dimensions"
      :theme="theme"
      :loading="loading"
      autoresize
    />
  </div>
</template>
