// data/sources/vue/line-chart/linechart.vue
<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { LineChart } from 'echarts/charts'
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { cn } from '@/lib/utils'
import type { LineChartProps } from './types'

defineOptions({
  name: 'UiLineChart',
})
import {
  buildEChartsOption,
  getResponsiveDimensions,
  transformDataToSeries,
} from './utils'

// Register ECharts components
use([
  LineChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  CanvasRenderer,
])

interface Props extends LineChartProps {
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  height: 300,
  theme: 'light',
  legend: true,
  legendPosition: 'top',
  grid: true,
  tooltip: true,
  animation: true,
  smooth: true,
  showPoints: true,
  pointSize: 6,
  area: false,
  stack: false,
  zoom: false,
  dataLabels: false,
  loading: false,
  emptyText: 'No data available',
})

// Build ECharts option
const chartOption = computed(() => {
  // Check for empty data
  if (!props.data || !props.data.datasets || props.data.datasets.length === 0) {
    return null
  }

  const baseOption = buildEChartsOption({
    ...props,
    chartType: 'line',
  })

  // Apply line-specific configurations
  const series = transformDataToSeries(props.data, 'line', {
    smooth: props.smooth,
    showSymbol: props.showPoints,
    symbolSize: props.pointSize,
    stack: props.stack ? 'total' : undefined,
    areaStyle: props.area
      ? {
          opacity: 0.3,
        }
      : undefined,
    label: props.dataLabels
      ? {
          show: true,
          position: 'top',
        }
      : undefined,
  })

  return {
    ...baseOption,
    series,
  }
})

// Get responsive dimensions
const dimensions = computed(() => getResponsiveDimensions(props.width, props.height))

// Loading option for ECharts
const loadingOption = computed(() => ({
  text: 'Loading...',
  color: '#3b82f6',
  textColor: '#666',
  maskColor: 'rgba(255, 255, 255, 0.8)',
  zlevel: 0,
}))
</script>

<template>
  <div :class="cn('galaxy-line-chart w-full', props.class)">
    <!-- Empty State -->
    <div
      v-if="!chartOption && !loading"
      class="flex items-center justify-center bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700"
      :style="{ height: dimensions.height }"
    >
      <p class="text-gray-500 dark:text-gray-400">{{ emptyText }}</p>
    </div>

    <!-- Chart -->
    <VChart
      v-else-if="chartOption"
      :option="chartOption"
      :style="dimensions"
      :theme="theme"
      :loading="loading"
      :loading-options="loadingOption"
      autoresize
    />
  </div>
</template>

<style scoped>
.galaxy-line-chart {
  position: relative;
}

/* Dark mode support */
:deep(.dark) .galaxy-line-chart {
  color-scheme: dark;
}
</style>

// data/sources/react-native/line-chart/LineChart.tsx
/**
 * Galaxy UI Charts - React Native LineChart Component
 *
 * A responsive line chart component powered by ECharts (react-native-echarts)
 */

import React, { useMemo } from 'react'
import { View, Text, Dimensions, StyleSheet } from 'react-native'
import { SkiaChart } from '@wuba/react-native-echarts'
import * as echarts from 'echarts/core'
import { LineChart as EChartsLineChart } from 'echarts/charts'
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
} from 'echarts/components'
import { SVGRenderer } from 'echarts/renderers'
import type { EChartsOption } from 'echarts'
import type { LineChartProps as BaseLineChartProps } from './types'
import {
  buildEChartsOption,
  transformDataToSeries,
} from './utils'

// Register ECharts components
echarts.use([
  EChartsLineChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  SVGRenderer,
])

export interface LineChartProps extends Omit<BaseLineChartProps, 'width'> {
  /**
   * Chart width (defaults to screen width - 32)
   */
  width?: number
  /**
   * Custom className (NativeWind support)
   */
  className?: string
}

export const LineChart: React.FC<LineChartProps> = ({
  data,
  height = 300,
  width,
  theme = 'light',
  legend = true,
  legendPosition = 'top',
  grid = true,
  tooltip = true,
  animation = true,
  smooth = true,
  showPoints = true,
  pointSize = 6,
  area = false,
  stack = false,
  zoom = false,
  dataLabels = false,
  loading = false,
  emptyText = 'No data available',
  className,
  options = {},
}) => {
  // Get screen width if not provided
  const chartWidth = width || Dimensions.get('window').width - 32

  // Build ECharts option
  const chartOption = useMemo<EChartsOption | null>(() => {
    // Check for empty data
    if (!data || !data.datasets || data.datasets.length === 0) {
      return null
    }

    const baseOption = buildEChartsOption({
      data,
      height,
      width: chartWidth,
      theme,
      legend,
      legendPosition,
      grid,
      tooltip,
      animation,
      zoom,
      options,
      chartType: 'line',
    })

    // Apply line-specific configurations
    const series = transformDataToSeries(data, 'line', {
      smooth,
      showSymbol: showPoints,
      symbolSize: pointSize,
      stack: stack ? 'total' : undefined,
      areaStyle: area
        ? {
            opacity: 0.3,
          }
        : undefined,
      label: dataLabels
        ? {
            show: true,
            position: 'top',
          }
        : undefined,
    })

    return {
      ...baseOption,
      series,
    } as EChartsOption
  }, [
    data,
    height,
    chartWidth,
    theme,
    legend,
    legendPosition,
    grid,
    tooltip,
    animation,
    smooth,
    showPoints,
    pointSize,
    area,
    stack,
    zoom,
    dataLabels,
    options,
  ])

  // Empty state
  if (!chartOption && !loading) {
    return (
      <View
        className={className}
        style={[
          styles.emptyContainer,
          {
            height,
            width: chartWidth,
          },
        ]}
      >
        <Text style={styles.emptyText}>{emptyText}</Text>
      </View>
    )
  }

  // Loading state
  if (loading) {
    return (
      <View
        className={className}
        style={[
          styles.loadingContainer,
          {
            height,
            width: chartWidth,
          },
        ]}
      >
        <Text style={styles.loadingText}>Loading...</Text>
      </View>
    )
  }

  // Render chart
  return (
    <View className={className} style={styles.container}>
      {chartOption && (
        <SkiaChart
          option={chartOption}
          width={chartWidth}
          height={height}
        />
      )}
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    position: 'relative',
  },
  emptyContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  emptyText: {
    color: '#6b7280',
    fontSize: 14,
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f9fafb',
    borderRadius: 8,
  },
  loadingText: {
    color: '#3b82f6',
    fontSize: 14,
  },
})

export default LineChart
