// data/sources/react-native/popover/Popover.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Popover component for displaying content in a floating popup
 */

import * as React from 'react';
import * as PopoverPrimitive from '@rn-primitives/popover';
import { cn } from '@/lib/utils';

/**
 * Popover root component
 * @property open - Controlled open state
 * @property defaultOpen - Uncontrolled initial open state
 * @property onOpenChange - Called when the open state changes
 */
const Popover = PopoverPrimitive.Root;

/**
 * Popover trigger component - wraps the element that triggers the popover
 */
const PopoverTrigger = PopoverPrimitive.Trigger;

const PopoverContent = React.forwardRef<
  React.ElementRef<typeof PopoverPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof PopoverPrimitive.Content>
>(({ className, align = 'center', sideOffset = 4, ...props }, ref) => (
  <PopoverPrimitive.Portal>
    <PopoverPrimitive.Content
      ref={ref}
      align={align}
      sideOffset={sideOffset}
      className={cn(
        'z-50 w-72 rounded-md border border-border bg-popover p-4 text-popover-foreground shadow-md',
        'data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2',
        className
      )}
      {...props}
    />
  </PopoverPrimitive.Portal>
));
PopoverContent.displayName = PopoverPrimitive.Content.displayName;

export { Popover, PopoverTrigger, PopoverContent };

// data/sources/angular/popover/popover.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Floating popover content triggered by click
 */

import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  RdxPopoverRootDirective,
  RdxPopoverTriggerDirective,
  RdxPopoverContentDirective,
} from '@radix-ng/primitives/popover';
import { cn } from '../../lib/utils';

@Component({
  selector: 'ui-popover',
  standalone: true,
  imports: [CommonModule, RdxPopoverRootDirective],
  template: `
    <div rdxPopoverRoot [open]="open">
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PopoverComponent {
  @Input() open = false;
  @Output() openChange = new EventEmitter<boolean>();

  onOpenChange(open: boolean): void {
    this.open = open;
    this.openChange.emit(open);
  }
}

@Component({
  selector: 'ui-popover-trigger',
  standalone: true,
  imports: [CommonModule, RdxPopoverTriggerDirective],
  template: `
    <button rdxPopoverTrigger [class]="triggerClasses" [disabled]="disabled">
      <ng-content></ng-content>
    </button>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PopoverTriggerComponent {
  @Input() class?: string;
  @Input() disabled = false;
  get triggerClasses(): string {
    return cn('disabled:pointer-events-none disabled:opacity-50', this.class);
  }
}

@Component({
  selector: 'ui-popover-content',
  standalone: true,
  imports: [CommonModule, RdxPopoverContentDirective],
  template: `
    <div rdxPopoverContent [class]="contentClasses">
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PopoverContentComponent {
  @Input() class?: string;

  get contentClasses(): string {
    return cn(
      'z-50 w-72 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2',
      this.class
    );
  }
}
