// data/sources/react-native/scatter-chart/ScatterChart.tsx
import React, { useMemo } from 'react';
import {
  View,
  Text,
  ActivityIndicator,
  useWindowDimensions,
} from 'react-native';
import { SkiaChart } from '@wuba/react-native-echarts';
import type { EChartsOption } from 'echarts';
import type { ScatterChartProps } from './types';
import { getDefaultColors } from './utils';

type ScatterPoint = [number, number] | [number, number, number];

function toScatterPoint(value: unknown, index: number): ScatterPoint {
  if (
    Array.isArray(value) &&
    typeof value[0] === 'number' &&
    typeof value[1] === 'number'
  ) {
    return typeof value[2] === 'number'
      ? [value[0], value[1], value[2]]
      : [value[0], value[1]];
  }

  if (value && typeof value === 'object') {
    const point = value as { x?: unknown; y?: unknown; value?: unknown };
    if (typeof point.x === 'number' && typeof point.y === 'number') {
      return typeof point.value === 'number'
        ? [point.x, point.y, point.value]
        : [point.x, point.y];
    }
  }

  return [index, typeof value === 'number' ? value : 0];
}

export interface ScatterChartComponentProps extends ScatterChartProps {
  style?: Record<string, unknown>;
}

export const ScatterChart: React.FC<ScatterChartComponentProps> = ({
  data,
  height = 300,
  width,
  theme = 'light',
  legend = true,
  legendPosition = 'top',
  loading = false,
  emptyText = 'No data available',
  symbolSize = 8,
  opacity = 0.8,
  xAxisLabel,
  yAxisLabel,
  style,
}) => {
  const { width: windowWidth } = useWindowDimensions();
  const chartWidth = typeof width === 'number' ? width : windowWidth - 32;

  const chartOption = useMemo<EChartsOption | null>(() => {
    if (!data || !data.datasets.length) {
      return null;
    }

    const colors = getDefaultColors();

    // Transform datasets to scatter series
    const series = data.datasets.map((dataset, index) => {
      const seriesData = dataset.data.map((value, i) =>
        toScatterPoint(value, i)
      );

      return {
        name: dataset.label,
        type: 'scatter',
        data: seriesData,
        symbolSize: (dataItem: ScatterPoint) => {
          // If third value exists, use it for size scaling
          if (typeof dataItem[2] === 'number') {
            return (Math.sqrt(dataItem[2]) * symbolSize) / 5;
          }
          return symbolSize;
        },
        itemStyle: {
          color: dataset.color || colors[index % colors.length],
          opacity: opacity,
        },
        emphasis: {
          focus: 'series',
          itemStyle: {
            borderColor: '#333',
            borderWidth: 1,
          },
        },
      };
    });

    return {
      tooltip: {
        trigger: 'item',
        confine: true,
        textStyle: {
          fontSize: 11,
        },
        formatter: ((params: { data?: ScatterPoint; seriesName?: string }) => {
          const dataPoint = params.data;
          if (!dataPoint) {
            return '';
          }

          return `${params.seriesName ?? ''}<br/>X: ${dataPoint[0]}<br/>Y: ${
            dataPoint[1]
          }${
            typeof dataPoint[2] === 'number'
              ? `<br/>Value: ${dataPoint[2]}`
              : ''
          }`;
        }) as never,
      },
      legend: legend
        ? {
            show: true,
            orient:
              legendPosition === 'left' || legendPosition === 'right'
                ? 'vertical'
                : 'horizontal',
            left:
              legendPosition === 'left'
                ? '5%'
                : legendPosition === 'right'
                ? 'auto'
                : 'center',
            right: legendPosition === 'right' ? '5%' : 'auto',
            top:
              legendPosition === 'top'
                ? '5%'
                : legendPosition === 'bottom'
                ? 'auto'
                : 'auto',
            bottom: legendPosition === 'bottom' ? '5%' : 'auto',
            textStyle: {
              fontSize: 10,
              color: theme === 'dark' ? '#e5e7eb' : '#374151',
            },
          }
        : {
            show: false,
          },
      grid: {
        left: '12%',
        right: '8%',
        bottom: '18%',
        top: legend ? '18%' : '12%',
        containLabel: true,
      },
      xAxis: {
        type: 'value',
        name: xAxisLabel,
        nameLocation: 'middle',
        nameGap: 25,
        nameTextStyle: {
          fontSize: 10,
          color: theme === 'dark' ? '#9ca3af' : '#6b7280',
        },
        axisLine: {
          lineStyle: {
            color: theme === 'dark' ? '#4b5563' : '#d1d5db',
          },
        },
        axisLabel: {
          fontSize: 9,
          color: theme === 'dark' ? '#9ca3af' : '#6b7280',
        },
        splitLine: {
          lineStyle: {
            color: theme === 'dark' ? '#374151' : '#e5e7eb',
          },
        },
      },
      yAxis: {
        type: 'value',
        name: yAxisLabel,
        nameLocation: 'middle',
        nameGap: 40,
        nameTextStyle: {
          fontSize: 10,
          color: theme === 'dark' ? '#9ca3af' : '#6b7280',
        },
        axisLine: {
          lineStyle: {
            color: theme === 'dark' ? '#4b5563' : '#d1d5db',
          },
        },
        axisLabel: {
          fontSize: 9,
          color: theme === 'dark' ? '#9ca3af' : '#6b7280',
        },
        splitLine: {
          lineStyle: {
            color: theme === 'dark' ? '#374151' : '#e5e7eb',
          },
        },
      },
      series,
    } as EChartsOption;
  }, [
    data,
    theme,
    legend,
    legendPosition,
    symbolSize,
    opacity,
    xAxisLabel,
    yAxisLabel,
  ]);

  if (loading) {
    return (
      <View
        style={[
          {
            height,
            width: chartWidth,
            justifyContent: 'center',
            alignItems: 'center',
          },
          style,
        ]}
      >
        <ActivityIndicator size="large" color="#3b82f6" />
      </View>
    );
  }

  if (!data || !data.datasets.length || !chartOption) {
    return (
      <View
        style={[
          {
            height,
            width: chartWidth,
            justifyContent: 'center',
            alignItems: 'center',
          },
          style,
        ]}
      >
        <Text style={{ color: '#6b7280', fontSize: 14 }}>{emptyText}</Text>
      </View>
    );
  }

  return (
    <View style={[{ height, width: chartWidth }, style]}>
      <SkiaChart option={chartOption} width={chartWidth} height={height} />
    </View>
  );
};

// data/sources/vue/scatter-chart/scatterchart.vue
<script setup lang="ts">
import { computed } from 'vue';
import VChart from 'vue-echarts';
import type { EChartsOption } from 'echarts';
import { use } from 'echarts/core';
import { ScatterChart } from 'echarts/charts';
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
} from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';
import type { ScatterChartProps } from './types';
import { getThemeColors } from './utils';

use([
  ScatterChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  CanvasRenderer,
]);

defineOptions({
  name: 'UiScatterChart',
});

const props = defineProps<ScatterChartProps>();

const chartOption = computed<EChartsOption>(() => {
  if (!props.data || !props.data.datasets.length) {
    return {};
  }

  const colors = getThemeColors(props.theme || 'light');

  // Transform datasets to scatter series
  const series = props.data.datasets.map((dataset, index) => {
    const seriesData = dataset.data.map((value: unknown, i: number) => {
      // Support both simple array [x, y] or object {x, y, value}
      if (Array.isArray(value)) {
        return value;
      } else if (
        typeof value === 'object' &&
        value &&
        'x' in value &&
        'y' in value
      ) {
        return [
          (value as Record<string, unknown>).x,
          (value as Record<string, unknown>).y,
          (value as Record<string, unknown>).value || 1,
        ];
      }
      // Fallback: use index as x, value as y
      return [i, value as number];
    });

    return {
      name: dataset.label,
      type: 'scatter' as const,
      data: seriesData,
      symbolSize: (data: number[]) => {
        // If third value exists, use it for size scaling
        if (data[2]) {
          return (Math.sqrt(data[2]) * (props.symbolSize || 10)) / 5;
        }
        return props.symbolSize || 10;
      },
      itemStyle: {
        color: dataset.color || colors[index % colors.length],
        opacity: props.opacity || 0.8,
      },
      emphasis: {
        focus: 'series',
        itemStyle: {
          borderColor: '#333',
          borderWidth: 1,
        },
      },
    };
  });

  return {
    tooltip: {
      trigger: 'item',
      confine: true,
      textStyle: {
        fontSize: 12,
      },
      formatter: (params: Record<string, unknown>) => {
        const data = params.data as unknown[];
        return `${params.seriesName}<br/>X: ${data[0]}<br/>Y: ${data[1]}${
          data[2] ? `<br/>Value: ${data[2]}` : ''
        }`;
      },
    },
    legend:
      props.legend !== false
        ? {
            show: true,
            orient:
              props.legendPosition === 'left' ||
              props.legendPosition === 'right'
                ? 'vertical'
                : 'horizontal',
            left:
              props.legendPosition === 'left'
                ? '5%'
                : props.legendPosition === 'right'
                ? 'auto'
                : 'center',
            right: props.legendPosition === 'right' ? '5%' : 'auto',
            top:
              props.legendPosition === 'top'
                ? '5%'
                : props.legendPosition === 'bottom'
                ? 'auto'
                : 'auto',
            bottom: props.legendPosition === 'bottom' ? '5%' : 'auto',
            textStyle: {
              fontSize: 12,
              color: props.theme === 'dark' ? '#e5e7eb' : '#374151',
            },
          }
        : {
            show: false,
          },
    grid: {
      left: '10%',
      right: '10%',
      bottom: '15%',
      top: props.legend !== false ? '15%' : '10%',
      containLabel: true,
    },
    xAxis: {
      type: 'value',
      name: props.xAxisLabel,
      nameLocation: 'middle',
      nameGap: 30,
      nameTextStyle: {
        fontSize: 12,
        color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
      },
      axisLine: {
        lineStyle: {
          color: props.theme === 'dark' ? '#4b5563' : '#d1d5db',
        },
      },
      axisLabel: {
        fontSize: 11,
        color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
      },
      splitLine: {
        lineStyle: {
          color: props.theme === 'dark' ? '#374151' : '#e5e7eb',
        },
      },
    },
    yAxis: {
      type: 'value',
      name: props.yAxisLabel,
      nameLocation: 'middle',
      nameGap: 50,
      nameTextStyle: {
        fontSize: 12,
        color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
      },
      axisLine: {
        lineStyle: {
          color: props.theme === 'dark' ? '#4b5563' : '#d1d5db',
        },
      },
      axisLabel: {
        fontSize: 11,
        color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
      },
      splitLine: {
        lineStyle: {
          color: props.theme === 'dark' ? '#374151' : '#e5e7eb',
        },
      },
    },
    series,
  };
});
</script>

<template>
  <div :style="{ height: `${height || 300}px`, width: width || '100%' }">
    <div v-if="loading" class="flex items-center justify-center h-full">
      <div
        class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"
      ></div>
    </div>
    <div
      v-else-if="!data || !data.datasets.length"
      class="flex items-center justify-center h-full text-gray-500"
    >
      {{ emptyText || 'No data available' }}
    </div>
    <VChart
      v-else
      :option="chartOption"
      :autoresize="true"
      class="w-full h-full"
    />
  </div>
</template>
