// data/sources/angular/separator/separator.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Visual divider with horizontal or vertical orientation
 */

import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RdxSeparatorRootDirective } from '@radix-ng/primitives/separator';
import { cn } from '../../lib/utils';

@Component({
  selector: 'ui-separator, [ui-separator]',
  standalone: true,
  imports: [CommonModule],
  template: ``,
  hostDirectives: [
    {
      directive: RdxSeparatorRootDirective,
      inputs: ['orientation']
    }
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SeparatorComponent {
  @Input() orientation: 'horizontal' | 'vertical' = 'horizontal';
  @Input() class?: string;

  @HostBinding('class')
  get hostClasses(): string {
    return cn(
      'shrink-0 bg-border',
      this.orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
      this.class
    );
  }
}

// data/sources/vue/separator/Separator.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Separator component - Visual divider with horizontal or vertical orientation
-->
<script setup lang="ts">
import { Separator as RadixSeparator, type SeparatorProps } from 'radix-vue'
import { cn } from '@/lib/utils'

defineOptions({
  name: 'UiSeparator',
})

const props = withDefaults(defineProps<SeparatorProps & { class?: string }>(), {
  orientation: 'horizontal',
  decorative: true,
})
</script>

<template>
  <RadixSeparator
    v-bind="props"
    :class="cn(
      'shrink-0 bg-border',
      props.orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
      props.class
    )"
  />
</template>
