// data/sources/react/bar-chart/BarChart.tsx
import React, { useMemo } from 'react'
import ReactECharts from 'echarts-for-react'
import type { EChartsOption } from 'echarts'
import { cn } from '@/lib/utils'
import type { BarChartProps } from './types'
import {
  buildEChartsOption,
  getResponsiveDimensions,
  transformDataToSeries,
} from './utils'

export interface BarChartComponentProps extends BarChartProps {
  className?: string
}

export const BarChart = React.forwardRef<ReactECharts, BarChartComponentProps>(
  (props, ref) => {
    const {
      data,
      height = 300,
      width = '100%',
      theme = 'light',
      legend = true,
      legendPosition = 'top',
      grid,
      tooltip,
      horizontal = false,
      stacked = false,
      showDataLabels = false,
      animation = true,
      loading = false,
      emptyText = 'No data available',
      className,
      options = {},
    } = props

    const chartOption = useMemo<EChartsOption | null>(() => {
      if (!data || !data.datasets || data.datasets.length === 0) {
        return null
      }

      const baseOption = buildEChartsOption({
        data,
        height,
        width,
        theme,
        legend,
        legendPosition,
        grid,
        tooltip,
        animation,
        options,
        chartType: 'bar',
      })

      // Transform data to bar series with additional config
      const series = transformDataToSeries(data, 'bar', {
        stack: stacked ? 'total' : undefined,
        label: showDataLabels
          ? {
              show: true,
              position: horizontal ? 'right' : 'top',
            }
          : undefined,
      })

      // Swap axes for horizontal bar chart
      if (horizontal) {
        return {
          ...baseOption,
          xAxis: {
            type: 'value',
            axisLine: {
              lineStyle: {
                color: theme === 'dark' ? '#52525b' : '#e4e4e7',
              },
            },
            axisLabel: {
              color: theme === 'dark' ? '#a1a1aa' : '#71717a',
              fontSize: 12,
            },
            splitLine: {
              lineStyle: {
                color: theme === 'dark' ? '#27272a' : '#f4f4f5',
                type: 'dashed',
              },
            },
          },
          yAxis: {
            type: 'category',
            data: data.labels,
            axisLine: {
              lineStyle: {
                color: theme === 'dark' ? '#52525b' : '#e4e4e7',
              },
            },
            axisLabel: {
              color: theme === 'dark' ? '#a1a1aa' : '#71717a',
              fontSize: 12,
            },
          },
          series,
        } as EChartsOption
      }

      return {
        ...baseOption,
        series,
      } as EChartsOption
    }, [
      data,
      height,
      width,
      theme,
      legend,
      legendPosition,
      grid,
      tooltip,
      animation,
      horizontal,
      stacked,
      showDataLabels,
      options,
    ])

    const dimensions = useMemo(() => {
      return getResponsiveDimensions(width, height)
    }, [width, height])

    // Loading state
    if (loading) {
      return (
        <div className={cn('galaxy-bar-chart w-full', className)}>
          <div
            style={{ height: `${height}px` }}
            className="flex items-center justify-center"
          >
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </div>
      )
    }

    // Empty state
    if (!chartOption) {
      return (
        <div className={cn('galaxy-bar-chart w-full', className)}>
          <div
            style={{ height: `${height}px` }}
            className="flex items-center justify-center border border-border rounded-md"
          >
            <p className="text-muted-foreground text-sm">{emptyText}</p>
          </div>
        </div>
      )
    }

    return (
      <div className={cn('galaxy-bar-chart w-full', className)}>
        <ReactECharts
          ref={ref}
          option={chartOption}
          style={dimensions}
          theme={theme}
          showLoading={loading}
          opts={{ renderer: 'canvas' }}
        />
      </div>
    )
  }
)

BarChart.displayName = 'BarChart'

// data/sources/angular/bar-chart/bar-chart.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Bar chart with horizontal/vertical orientation and stacked mode
 */

import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core'
import { CommonModule } from '@angular/common'
import { NgxEchartsModule } from 'ngx-echarts'
import type { EChartsOption } from 'echarts'
import type { BarChartProps, ChartData } from './types'
import {
  buildEChartsOption,
  getResponsiveDimensions,
  transformDataToSeries,
} from './utils'

@Component({
  selector: 'ui-bar-chart',
  standalone: true,
  imports: [CommonModule, NgxEchartsModule],
  template: `
    <div [class]="containerClass">
      <!-- Loading state -->
      <div
        *ngIf="loading"
        [style.height]="dimensions.height"
        class="flex items-center justify-center"
      >
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>

      <!-- Empty state -->
      <div
        *ngIf="!chartOption && !loading"
        [style.height]="dimensions.height"
        class="flex items-center justify-center border border-border rounded-md"
      >
        <p class="text-muted-foreground text-sm">{{ emptyText }}</p>
      </div>

      <!-- Chart -->
      <div
        *ngIf="chartOption && !loading"
        echarts
        [options]="chartOption"
        [theme]="theme"
        [loading]="loading"
        [style.height]="dimensions.height"
        [style.width]="dimensions.width"
        class="galaxy-bar-chart"
      ></div>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
      }
    `,
  ],
})
export class BarChartComponent implements OnInit, OnChanges, BarChartProps {
  @Input({ required: true }) data!: ChartData
  @Input() height: number = 300
  @Input() width?: number | string = '100%'
  @Input() theme: 'light' | 'dark' = 'light'
  @Input() legend: boolean = true
  @Input() legendPosition: 'top' | 'bottom' | 'left' | 'right' = 'top'
  @Input() grid?: boolean | Record<string, unknown>
  @Input() tooltip?: boolean | Record<string, unknown>
  @Input() animation: boolean = true
  @Input() horizontal: boolean = false
  @Input() stacked: boolean = false
  @Input() showDataLabels: boolean = false
  @Input() loading: boolean = false
  @Input() emptyText: string = 'No data available'
  @Input() class?: string
  @Input() options?: Record<string, unknown> = {}

  chartOption: EChartsOption | null = null
  dimensions: { width: string; height: string } = { width: '100%', height: '300px' }

  get containerClass(): string {
    return `galaxy-bar-chart-container w-full ${this.class || ''}`
  }

  ngOnInit(): void {
    this.updateChart()
    this.updateDimensions()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['data'] || changes['theme'] || changes['horizontal'] || changes['stacked']) {
      this.updateChart()
    }
    if (changes['width'] || changes['height']) {
      this.updateDimensions()
    }
  }

  private updateChart(): void {
    if (!this.data || !this.data.datasets || this.data.datasets.length === 0) {
      this.chartOption = null
      return
    }

    const baseOption = buildEChartsOption({
      data: this.data,
      height: this.height,
      width: this.width,
      theme: this.theme,
      legend: this.legend,
      legendPosition: this.legendPosition,
      grid: this.grid,
      tooltip: this.tooltip,
      animation: this.animation,
      options: this.options,
      chartType: 'bar',
    })

    // Transform data to bar series with additional config
    const series = transformDataToSeries(this.data, 'bar', {
      stack: this.stacked ? 'total' : undefined,
      label: this.showDataLabels
        ? {
            show: true,
            position: this.horizontal ? 'right' : 'top',
          }
        : undefined,
    })

    // Swap axes for horizontal bar chart
    if (this.horizontal) {
      this.chartOption = {
        ...baseOption,
        xAxis: baseOption.yAxis,
        yAxis: {
          type: 'category' as const,
          data: this.data.labels,
          axisLine: {
            lineStyle: {
              color: this.theme === 'dark' ? '#52525b' : '#e4e4e7',
            },
          },
          axisLabel: {
            color: this.theme === 'dark' ? '#a1a1aa' : '#71717a',
            fontSize: 12,
          },
        },
        series: series as EChartsOption['series'],
      } as EChartsOption
    } else {
      this.chartOption = {
        ...baseOption,
        series,
      } as EChartsOption
    }
  }

  private updateDimensions(): void {
    this.dimensions = getResponsiveDimensions(this.width, this.height)
  }
}
