// data/sources/vue/progress/Progress.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Progress component - Progress bar indicator with percentage value
-->
<script setup lang="ts">
import { computed } from 'vue';
import { ProgressIndicator, ProgressRoot } from 'radix-vue';
import { cn } from '@/lib/utils';

defineOptions({
  name: 'UiProgress',
})

/**
 * Progress Props
 * @prop modelValue - Current progress value (0-max)
 * @prop max - Maximum value
 * @prop class - CSS class names for the progress bar
 */
interface ProgressProps {
  /** Current progress value (0-max). */
  modelValue?: number | null
  /** Maximum value. */
  max?: number
  /** CSS class names for the progress bar. */
  class?: string
}

const props = withDefaults(defineProps<ProgressProps>(), {
  modelValue: 0,
  max: 100,
})

const percentage = computed(() => {
  const value = props.modelValue ?? 0;
  return Math.min(Math.max((value / props.max) * 100, 0), 100);
});
</script>

<template>
  <ProgressRoot
    :model-value="modelValue"
    :max="max"
    :class="cn('relative h-2 w-full overflow-hidden rounded-full bg-secondary', props.class)"
  >
    <ProgressIndicator
      class="h-full w-full flex-1 bg-primary transition-all"
      :style="`transform: translateX(-${100 - percentage}%)`"
    />
  </ProgressRoot>
</template>

// data/sources/angular/progress/progress.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Progress bar indicator with percentage display
 */

import { Component, Input, ChangeDetectionStrategy, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  RdxProgressRootDirective,
  RdxProgressIndicatorDirective,
} from '@radix-ng/primitives/progress';
import { cn } from '../../lib/utils';

@Component({
  selector: 'ui-progress',
  standalone: true,
  imports: [CommonModule, RdxProgressRootDirective, RdxProgressIndicatorDirective],
  template: `
    <div
      rdxProgressRoot
      [(value)]="_value"
      [(max)]="_max"
      [class]="rootClasses()"
    >
      <div
        rdxProgressIndicator
        class="h-full w-full flex-1 bg-primary transition-all"
        [style.transform]="'translateX(-' + (100 - percentage()) + '%)'"
      ></div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProgressComponent {
  @Input() set value(val: number | null | undefined) {
    this._value.set(val ?? 0);
  }
  @Input() set max(val: number) {
    this._max.set(val);
  }
  @Input() class?: string;

  protected _value = signal<number>(0);
  protected _max = signal<number>(100);

  protected percentage = computed(() => {
    const val = this._value();
    const maxVal = this._max();
    return Math.min(Math.max((val / maxVal) * 100, 0), 100);
  });

  protected rootClasses = computed(() => {
    return cn(
      'relative h-2 w-full overflow-hidden rounded-full bg-secondary',
      this.class
    );
  });
}
