// data/sources/angular/spinner/spinner.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Loading spinner with 3 size variants
 */

import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { cn } from '../../lib/utils';

export type SpinnerSize = 'sm' | 'default' | 'lg';

@Component({
  selector: 'ui-spinner',
  standalone: true,
  template: `
    <span
      role="status"
      [attr.aria-label]="label"
      [class]="spinnerClasses"
    ></span>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SpinnerComponent {
  @Input() size: SpinnerSize = 'default';
  @Input() label: string = 'Loading...';
  @Input() class?: string;

  get spinnerClasses(): string {
    return cn(
      'inline-block shrink-0 animate-spin rounded-full border-solid border-current border-t-transparent text-muted-foreground',
      {
        'h-4 w-4 border-2': this.size === 'sm',
        'h-6 w-6 border-2': this.size === 'default',
        'h-8 w-8 border-[3px]': this.size === 'lg',
      },
      this.class,
    );
  }
}

// data/sources/vue/spinner/Spinner.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Spinner component - Loading indicator with 3 size variants (sm, default, lg)
-->
<script setup lang="ts">
import { computed, type HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

defineOptions({
  name: 'UiSpinner',
})

export type SpinnerSize = 'sm' | 'default' | 'lg'

interface Props {
  size?: SpinnerSize
  label?: string
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<Props>(), {
  size: 'default',
  label: 'Loading...',
})

const sizeClasses: Record<SpinnerSize, string> = {
  sm: 'h-4 w-4 border-2',
  default: 'h-6 w-6 border-2',
  lg: 'h-8 w-8 border-[3px]',
}

const className = computed(() =>
  cn(
    'inline-block shrink-0 animate-spin rounded-full border-solid border-current border-t-transparent text-muted-foreground',
    sizeClasses[props.size],
    props.class
  )
)
</script>

<template>
  <span role="status" :aria-label="label" :class="className" />
</template>
