// data/sources/vue/label/Label.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Label component - Renders an accessible label associated with controls
-->
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { Label as RadixLabel, type LabelProps as RadixLabelProps } from 'radix-vue'
import { cn } from '@/lib/utils'

defineOptions({
  name: 'UiLabel',
})

/**
 * Label Props
 * @prop for - Id of the element the label is associated with
 * @prop asChild - Render as child via Radix Primitive
 * @prop as - Element or component to render
 * @prop class - CSS class names for the label
 */
interface LabelProps extends RadixLabelProps {
  /** Id of the element the label is associated with. */
  htmlFor?: string
  /** Render as child via Radix Primitive. */
  asChild?: boolean
  /** Element or component to render. */
  as?: string
  /** CSS class names for the label. */
  class?: HTMLAttributes['class']
}

const props = defineProps<LabelProps>()

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <RadixLabel
    :class="cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      props.class
    )"
    v-bind="delegatedProps"
  >
    <slot />
  </RadixLabel>
</template>

// data/sources/react-native/label/Label.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Label component for form field labels with required indicator support
 */

import * as React from 'react';
import { Text, TextProps } from 'react-native';
import { cn } from '@/lib/utils';

export interface LabelProps extends TextProps {
  /** Label content */
  children?: React.ReactNode;
  /** Marks label as required and appends an asterisk */
  required?: boolean;
  /** CSS class names for the label */
  className?: string;
}

const Label = React.forwardRef<React.ElementRef<typeof Text>, LabelProps>(
  ({ className, children, required, ...props }, ref) => {
    return (
      <Text
        ref={ref}
        className={cn(
          'text-sm font-medium text-foreground leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
          className
        )}
        {...props}
      >
        {children}
        {required && <Text className="text-destructive ml-1">*</Text>}
      </Text>
    );
  }
);

Label.displayName = 'Label';

export { Label };
