// data/sources/vue/pie-chart/piechart.vue
<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { PieChart } from 'echarts/charts'
import {
  TitleComponent,
  TooltipComponent,
  LegendComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { cn } from '@/lib/utils'
import type { PieChartProps } from './types'
import { getDefaultColors, formatNumber } from './utils'

defineOptions({
  name: 'UiPieChart',
})

// Register ECharts components
use([
  PieChart,
  TitleComponent,
  TooltipComponent,
  LegendComponent,
  CanvasRenderer,
])

export interface Props extends PieChartProps {
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  height: 300,
  width: '100%',
  theme: 'light',
  legend: true,
  legendPosition: 'right',
  animation: true,
  innerRadius: 0,
  outerRadius: 70,
  showPercentage: true,
  labelPosition: 'outside',
  loading: false,
  emptyText: 'No data available',
})

const chartOption = computed(() => {
  if (!props.data || !props.data.datasets || props.data.datasets.length === 0) {
    return null
  }

  const colors = getDefaultColors()
  const dataset = props.data.datasets[0] // Pie charts typically use first dataset
  if (!dataset) return {}

  const total = dataset.data.reduce((sum, val) => sum + val, 0)

  const pieData = props.data.labels.map((label, index) => ({
    name: label,
    value: dataset.data[index],
    itemStyle: {
      color: dataset.backgroundColor?.[index] || colors[index % colors.length],
    },
  }))

  return {
    backgroundColor: 'transparent',
    color: colors,
    tooltip: {
      trigger: 'item',
      formatter: (params: Record<string, unknown>) => {
        const percent = (((params.value as number) / total) * 100).toFixed(1)
        return `${params.name}: ${formatNumber(params.value as number)} (${percent}%)`
      },
      backgroundColor: props.theme === 'dark' ? '#18181b' : '#ffffff',
      borderColor: props.theme === 'dark' ? '#27272a' : '#e4e4e7',
      textStyle: {
        color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
      },
    },
    legend: props.legend
      ? {
          orient: props.legendPosition === 'left' || props.legendPosition === 'right'
            ? 'vertical'
            : 'horizontal',
          [props.legendPosition]: props.legendPosition === 'top' || props.legendPosition === 'bottom'
            ? 'center'
            : '0',
          [props.legendPosition === 'top' || props.legendPosition === 'bottom'
            ? props.legendPosition
            : 'middle']: '0',
          textStyle: {
            color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
          },
        }
      : undefined,
    series: [
      {
        type: 'pie',
        radius: [`${props.innerRadius}%`, `${props.outerRadius}%`],
        center: ['50%', '50%'],
        data: pieData,
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)',
          },
        },
        label: {
          show: props.labelPosition !== 'center',
          position: props.labelPosition === 'inside' ? 'inside' : 'outside',
          formatter: props.showPercentage
            ? (params: Record<string, unknown>) => {
                const percent = (((params.value as number) / total) * 100).toFixed(1)
                return `${params.name}\n${percent}%`
              }
            : '{b}',
          color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
        },
        labelLine: {
          show: props.labelPosition === 'outside',
        },
      },
    ],
  }
})

const dimensions = computed(() => {
  return {
    height: `${props.height}px`,
    width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  }
})
</script>

<template>
  <div :class="cn('galaxy-pie-chart w-full', props.class)">
    <!-- Loading state -->
    <div
      v-if="loading"
      :style="{ height: `${height}px` }"
      class="flex items-center justify-center"
    >
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
    </div>

    <!-- Empty state -->
    <div
      v-else-if="!chartOption"
      :style="{ height: `${height}px` }"
      class="flex items-center justify-center border border-border rounded-md"
    >
      <p class="text-muted-foreground text-sm">{{ emptyText }}</p>
    </div>

    <!-- Chart -->
    <VChart
      v-else
      :option="chartOption"
      :style="dimensions"
      :theme="theme"
      :loading="loading"
      autoresize
    />
  </div>
</template>

// data/sources/angular/pie-chart/pie-chart.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Pie Chart component - Responsive pie chart powered by ECharts
 */

import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core'
import { CommonModule } from '@angular/common'
import { NgxEchartsModule } from 'ngx-echarts'
import type { EChartsOption } from 'echarts'
import type { PieChartProps, ChartData } from './types'
import { getDefaultColors, formatNumber } from './utils'

@Component({
  selector: 'ui-pie-chart',
  standalone: true,
  imports: [CommonModule, NgxEchartsModule],
  template: `
    <div [class]="containerClass">
      <!-- Loading state -->
      <div
        *ngIf="loading"
        [style.height]="dimensions.height"
        class="flex items-center justify-center"
      >
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>

      <!-- Empty state -->
      <div
        *ngIf="!chartOption && !loading"
        [style.height]="dimensions.height"
        class="flex items-center justify-center border border-border rounded-md"
      >
        <p class="text-muted-foreground text-sm">{{ emptyText }}</p>
      </div>

      <!-- Chart -->
      <div
        *ngIf="chartOption && !loading"
        echarts
        [options]="chartOption"
        [theme]="theme"
        [loading]="loading"
        [style.height]="dimensions.height"
        [style.width]="dimensions.width"
        class="galaxy-pie-chart"
      ></div>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
      }
    `,
  ],
})
export class PieChartComponent implements OnInit, OnChanges, PieChartProps {
  @Input({ required: true }) data!: ChartData
  @Input() height: number = 300
  @Input() width?: number | string = '100%'
  @Input() theme: 'light' | 'dark' = 'light'
  @Input() legend: boolean = true
  @Input() legendPosition: 'top' | 'bottom' | 'left' | 'right' = 'right'
  @Input() animation: boolean = true
  @Input() innerRadius: number = 0
  @Input() outerRadius: number = 70
  @Input() showPercentage: boolean = true
  @Input() labelPosition: 'inside' | 'outside' | 'center' = 'outside'
  @Input() loading: boolean = false
  @Input() emptyText: string = 'No data available'
  @Input() class?: string
  @Input() options?: Record<string, unknown> = {}

  chartOption: EChartsOption | null = null
  dimensions: { width: string; height: string } = { width: '100%', height: '300px' }

  get containerClass(): string {
    return `galaxy-pie-chart-container w-full ${this.class || ''}`
  }

  ngOnInit(): void {
    this.updateChart()
    this.updateDimensions()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['data'] || changes['theme'] || changes['innerRadius'] || changes['showPercentage']) {
      this.updateChart()
    }
    if (changes['width'] || changes['height']) {
      this.updateDimensions()
    }
  }

  private updateChart(): void {
    if (!this.data || !this.data.datasets || this.data.datasets.length === 0) {
      this.chartOption = null
      return
    }

    const colors = getDefaultColors()
    const dataset = this.data.datasets[0]
    const total = dataset.data.reduce((sum: number, val: number) => sum + val, 0)

    const pieData = this.data.labels.map((label: string, index: number) => ({
      name: label,
      value: dataset.data[index],
      itemStyle: {
        color: dataset.backgroundColor?.[index] || colors[index % colors.length],
      },
    }))

    this.chartOption = {
      backgroundColor: 'transparent',
      color: colors,
      tooltip: {
        trigger: 'item',
        formatter: (params: { name: string; value: number }): string => {
          const percent = ((params.value / total) * 100).toFixed(1)
          return `${params.name}: ${formatNumber(params.value)} (${percent}%)`
        },
        backgroundColor: this.theme === 'dark' ? '#18181b' : '#ffffff',
        borderColor: this.theme === 'dark' ? '#27272a' : '#e4e4e7',
        textStyle: {
          color: this.theme === 'dark' ? '#fafafa' : '#0a0a0a',
        },
      },
      legend: this.legend
        ? {
            orient: this.legendPosition === 'left' || this.legendPosition === 'right'
              ? 'vertical'
              : 'horizontal',
            [this.legendPosition]: this.legendPosition === 'top' || this.legendPosition === 'bottom'
              ? 'center'
              : '0',
            [this.legendPosition === 'top' || this.legendPosition === 'bottom'
              ? this.legendPosition
              : 'middle']: '0',
            textStyle: {
              color: this.theme === 'dark' ? '#fafafa' : '#0a0a0a',
            },
          }
        : undefined,
      series: [
        {
          type: 'pie',
          radius: [`${this.innerRadius}%`, `${this.outerRadius}%`],
          center: ['50%', '50%'],
          data: pieData,
          emphasis: {
            itemStyle: {
              shadowBlur: 10,
              shadowOffsetX: 0,
              shadowColor: 'rgba(0, 0, 0, 0.5)',
            },
          },
          label: {
            show: this.labelPosition !== 'center',
            position: this.labelPosition === 'inside' ? 'inside' : 'outside',
            formatter: this.showPercentage
              ? (params: { name: string; value: number }): string => {
                  const percent = ((params.value / total) * 100).toFixed(1)
                  return `${params.name}\n${percent}%`
                }
              : '{b}',
            color: this.theme === 'dark' ? '#fafafa' : '#0a0a0a',
          },
          labelLine: {
            show: this.labelPosition === 'outside',
          },
        },
      ],
      ...this.options,
    }
  }

  private updateDimensions(): void {
    this.dimensions = {
      height: `${this.height}px`,
      width: typeof this.width === 'number' ? `${this.width}px` : this.width || '100%',
    }
  }
}
