// data/sources/vue/bar-chart/barchart.vue
<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { BarChart } from 'echarts/charts'
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { cn } from '@/lib/utils'
import type { BarChartProps } from './types'

defineOptions({
  name: 'UiBarChart',
})
import {
  buildEChartsOption,
  getResponsiveDimensions,
  transformDataToSeries,
} from './utils'

// Register ECharts components
use([
  BarChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  CanvasRenderer,
])

export interface Props extends BarChartProps {
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  height: 300,
  width: '100%',
  theme: 'light',
  legend: true,
  legendPosition: 'top',
  animation: true,
  horizontal: false,
  stacked: false,
  showDataLabels: false,
  loading: false,
  emptyText: 'No data available',
})

const chartOption = computed(() => {
  if (!props.data || !props.data.datasets || props.data.datasets.length === 0) {
    return null
  }

  const baseOption = buildEChartsOption({
    ...props,
    chartType: 'bar',
  })

  // Transform data to bar series with additional config
  const series = transformDataToSeries(props.data, 'bar', {
    stack: props.stacked ? 'total' : undefined,
    label: props.showDataLabels
      ? {
          show: true,
          position: props.horizontal ? 'right' : 'top',
        }
      : undefined,
  })

  // Swap axes for horizontal bar chart
  if (props.horizontal) {
    return {
      ...baseOption,
      xAxis: baseOption.yAxis,
      yAxis: {
        type: 'category',
        data: props.data.labels,
        axisLine: {
          lineStyle: {
            color: props.theme === 'dark' ? '#52525b' : '#e4e4e7',
          },
        },
        axisLabel: {
          color: props.theme === 'dark' ? '#a1a1aa' : '#71717a',
          fontSize: 12,
        },
      },
      series,
    }
  }

  return {
    ...baseOption,
    series,
  }
})

const dimensions = computed(() => {
  return getResponsiveDimensions(props.width, props.height)
})
</script>

<template>
  <div :class="cn('galaxy-bar-chart w-full', props.class)">
    <!-- Loading state -->
    <div
      v-if="loading"
      :style="{ height: `${height}px` }"
      class="flex items-center justify-center"
    >
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
    </div>

    <!-- Empty state -->
    <div
      v-else-if="!chartOption"
      :style="{ height: `${height}px` }"
      class="flex items-center justify-center border border-border rounded-md"
    >
      <p class="text-muted-foreground text-sm">{{ emptyText }}</p>
    </div>

    <!-- Chart -->
    <VChart
      v-else
      :option="chartOption"
      :style="dimensions"
      :theme="theme"
      :loading="loading"
      autoresize
    />
  </div>
</template>

// data/sources/react-native/bar-chart/BarChart.tsx
import React, { useMemo } from 'react'
import { View, Text, Dimensions, ActivityIndicator } from 'react-native'
import { SkiaChart } from '@wuba/react-native-echarts'
import * as echarts from 'echarts/core'
import { BarChart as EChartsBarChart } from 'echarts/charts'
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
} from 'echarts/components'
import { SVGRenderer } from 'echarts/renderers'
import type { EChartsOption } from 'echarts'
import type { BarChartProps } from './types'
import {
  buildEChartsOption,
  transformDataToSeries,
} from './utils'

// Register ECharts components
echarts.use([
  EChartsBarChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  SVGRenderer,
])

export interface BarChartComponentProps extends BarChartProps {
  className?: string
  stacked?: boolean
  showDataLabels?: boolean
}

export const BarChart: React.FC<BarChartComponentProps> = ({
  data,
  height = 300,
  width,
  theme = 'light',
  legend = true,
  legendPosition = 'top',
  grid,
  tooltip,
  animation = true,
  horizontal = false,
  stacked = false,
  showDataLabels = false,
  loading = false,
  emptyText = 'No data available',
  className,
  options = {},
}) => {
  const chartWidth = typeof width === 'number' ? width : Dimensions.get('window').width - 32

  const chartOption = useMemo<EChartsOption | null>(() => {
    if (!data || !data.datasets || data.datasets.length === 0) {
      return null
    }

    const baseOption = buildEChartsOption({
      data,
      height,
      width: chartWidth,
      theme,
      legend,
      legendPosition,
      grid,
      tooltip,
      animation,
      options,
      chartType: 'bar',
    })

    // Transform data to bar series with additional config
    const series = transformDataToSeries(data, 'bar', {
      stack: stacked ? 'total' : undefined,
      label: showDataLabels
        ? {
            show: true,
            position: horizontal ? 'right' : 'top',
            fontSize: 10, // Smaller for mobile
          }
        : undefined,
    })

    // Swap axes for horizontal bar chart
    if (horizontal) {
      return {
        ...baseOption,
        xAxis: baseOption.yAxis,
        yAxis: {
          type: 'category',
          data: data.labels,
          axisLine: {
            lineStyle: {
              color: theme === 'dark' ? '#52525b' : '#e4e4e7',
            },
          },
          axisLabel: {
            color: theme === 'dark' ? '#a1a1aa' : '#71717a',
            fontSize: 11,
            rotate: data.labels.length > 6 ? 45 : 0,
          },
        },
        series,
      } as EChartsOption
    }

    return {
      ...baseOption,
      series,
    } as EChartsOption
  }, [
    data,
    height,
    chartWidth,
    theme,
    legend,
    legendPosition,
    grid,
    tooltip,
    animation,
    horizontal,
    stacked,
    showDataLabels,
    options,
  ])

  // Loading state
  if (loading) {
    return (
      <View
        className={className}
        style={{
          height,
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <ActivityIndicator size="large" />
      </View>
    )
  }

  // Empty state
  if (!chartOption) {
    return (
      <View
        className={className}
        style={{
          height,
          justifyContent: 'center',
          alignItems: 'center',
          borderWidth: 1,
          borderColor: theme === 'dark' ? '#27272a' : '#e4e4e7',
          borderRadius: 8,
        }}
      >
        <Text
          style={{
            color: theme === 'dark' ? '#a1a1aa' : '#71717a',
            fontSize: 14,
          }}
        >
          {emptyText}
        </Text>
      </View>
    )
  }

  return (
    <View className={className}>
      <SkiaChart option={chartOption} width={chartWidth} height={height} />
    </View>
  )
}
