// data/sources/vue/input/Input.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Input component - Displays a form input field or a component that looks like an input field
-->
<script setup lang="ts">
import { type HTMLAttributes } from 'vue'
import { useVModel } from '@vueuse/core'
import { cn } from '@/lib/utils'

defineOptions({
  name: 'UiInput',
})

/**
 * Input Props
 * @prop type - Input type
 * @prop modelValue - Controlled value
 * @prop class - CSS class names for the input
 * @prop disabled - Disables the input
 * @prop placeholder - Placeholder text
 * @event update:modelValue - Emitted when the value changes
 */
interface InputProps {
  /** Input type. */
  type?: string
  /** Controlled value. */
  modelValue?: string | number
  /** CSS class names for the input. */
  class?: HTMLAttributes['class']
  /** Disables the input. */
  disabled?: boolean
  /** Placeholder text. */
  placeholder?: string
}

const props = withDefaults(defineProps<InputProps>(), {
  type: 'text',
  disabled: false,
})

const emits = defineEmits<{
  'update:modelValue': [value: string | number]
}>()

const modelValue = useVModel(props, 'modelValue', emits, {
  passive: true,
  defaultValue: '',
})
</script>

<template>
  <input
    v-model="modelValue"
    :type="type"
    :class="cn(
      'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
      props.class
    )"
    :disabled="disabled"
    :placeholder="placeholder"
  />
</template>

// data/sources/react-native/input/Input.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Text input component with label, placeholder, and error states
 */

import * as React from 'react';
import { TextInput, TextInputProps, View, Text } from 'react-native';
import { cn } from '@/lib/utils';

export interface InputProps extends TextInputProps {
  /** Controlled value */
  value?: string;
  /** Placeholder text */
  placeholder?: string;
  /** Whether the input is editable */
  editable?: boolean;
  /** Change handler */
  onChangeText?: (text: string) => void;
  /** Blur handler */
  onBlur?: TextInputProps['onBlur'];
  /** Focus handler */
  onFocus?: TextInputProps['onFocus'];
  /** CSS class names for the input */
  className?: string;
  /** Label text */
  label?: string;
  /** Error text */
  error?: string;
  /** Wrapper class name */
  containerClassName?: string;
  /** Label class name */
  labelClassName?: string;
  /** Error text class name */
  errorClassName?: string;
}

const Input = React.forwardRef<React.ElementRef<typeof TextInput>, InputProps>(
  ({ className, containerClassName, label, error, labelClassName, errorClassName, ...props }, ref) => {
    return (
      <View className={cn('flex flex-col gap-1.5', containerClassName)}>
        {label && (
          <Text className={cn('text-sm font-medium text-foreground', labelClassName)}>
            {label}
          </Text>
        )}
        <TextInput
          ref={ref}
          className={cn(
            'h-10 rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground',
            'focus:border-ring focus:ring-2 focus:ring-ring focus:ring-offset-2',
            'disabled:cursor-not-allowed disabled:opacity-50',
            error && 'border-destructive focus:border-destructive focus:ring-destructive',
            className
          )}
          placeholderTextColor="rgb(156 163 175)" // text-muted-foreground
          {...props}
        />
        {error && (
          <Text className={cn('text-sm text-destructive', errorClassName)}>
            {error}
          </Text>
        )}
      </View>
    );
  }
);

Input.displayName = 'Input';

export { Input };
