// data/sources/vue/mixed-chart/mixedchart.vue
<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { LineChart, BarChart } from 'echarts/charts'
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { cn } from '@/lib/utils'
import type { MixedChartProps } from './types'
import { getDefaultColors } from './utils'

defineOptions({
  name: 'UiMixedChart',
})

// Register ECharts components
use([
  LineChart,
  BarChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  CanvasRenderer,
])

export interface Props extends MixedChartProps {
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  height: 300,
  theme: 'light',
  legend: true,
  legendPosition: 'top',
  grid: true,
  tooltip: true,
  animation: true,
  loading: false,
  emptyText: 'No data available',
})

// Build ECharts option
const chartOption = computed(() => {
  if (!props.data || !props.data.datasets || props.data.datasets.length === 0) {
    return null
  }

  const colors = getDefaultColors()

  // Build series with mixed types
  const series = props.data.datasets.map((dataset, index) => {
    const chartType = dataset.type || 'line'
    const color = dataset.color || colors[index % colors.length]

    const baseSeries = {
      name: dataset.label,
      type: chartType,
      data: dataset.data,
      itemStyle: {
        color: color,
      },
    }

    // Add type-specific configurations
    if (chartType === 'line') {
      return {
        ...baseSeries,
        smooth: dataset.smooth !== false,
        showSymbol: true,
        symbolSize: 6,
        lineStyle: {
          width: 2,
        },
      }
    } else if (chartType === 'bar') {
      return {
        ...baseSeries,
        barMaxWidth: 50,
      }
    } else if (chartType === 'area') {
      return {
        ...baseSeries,
        type: 'line',
        smooth: true,
        showSymbol: true,
        symbolSize: 6,
        areaStyle: {
          opacity: 0.3,
        },
      }
    }

    return baseSeries
  })

  return {
    backgroundColor: 'transparent',
    color: colors,
    tooltip: props.tooltip
      ? {
          trigger: 'axis',
          axisPointer: {
            type: 'cross',
            crossStyle: {
              color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
            },
          },
          backgroundColor: props.theme === 'dark' ? '#18181b' : '#ffffff',
          borderColor: props.theme === 'dark' ? '#27272a' : '#e4e4e7',
          textStyle: {
            color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
          },
        }
      : undefined,
    legend: props.legend
      ? {
          data: props.data.datasets.map((d) => d.label),
          [props.legendPosition]: props.legendPosition === 'top' || props.legendPosition === 'bottom' ? 'center' : '5%',
          [props.legendPosition === 'left' || props.legendPosition === 'right' ? 'top' : props.legendPosition]: props.legendPosition === 'left' || props.legendPosition === 'right' ? 'middle' : '5%',
          orient: props.legendPosition === 'left' || props.legendPosition === 'right' ? 'vertical' : 'horizontal',
          textStyle: {
            color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
          },
        }
      : undefined,
    grid: props.grid
      ? {
          left: '3%',
          right: '4%',
          bottom: '3%',
          top: props.legend && props.legendPosition === 'top' ? '15%' : '10%',
          containLabel: true,
        }
      : undefined,
    xAxis: {
      type: 'category',
      data: props.data.labels,
      boundaryGap: true,
      axisLine: {
        lineStyle: {
          color: props.theme === 'dark' ? '#4b5563' : '#d1d5db',
        },
      },
      axisLabel: {
        color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
      },
    },
    yAxis: {
      type: 'value',
      axisLine: {
        lineStyle: {
          color: props.theme === 'dark' ? '#4b5563' : '#d1d5db',
        },
      },
      axisLabel: {
        color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
      },
      splitLine: {
        lineStyle: {
          color: props.theme === 'dark' ? '#374151' : '#e5e7eb',
        },
      },
    },
    series,
  }
})

// Get responsive dimensions
const dimensions = computed(() => ({
  height: `${props.height}px`,
  width: typeof props.width === 'number' ? `${props.width}px` : props.width || '100%',
}))

// Loading option for ECharts
const loadingOption = computed(() => ({
  text: 'Loading...',
  color: '#3b82f6',
  textColor: '#666',
  maskColor: 'rgba(255, 255, 255, 0.8)',
  zlevel: 0,
}))
</script>

<template>
  <div :class="cn('galaxy-mixed-chart w-full', props.class)">
    <!-- Empty State -->
    <div
      v-if="!chartOption && !loading"
      class="flex items-center justify-center bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700"
      :style="{ height: dimensions.height }"
    >
      <p class="text-gray-500 dark:text-gray-400">{{ emptyText }}</p>
    </div>

    <!-- Chart -->
    <VChart
      v-else-if="chartOption"
      :option="chartOption"
      :style="dimensions"
      :theme="theme"
      :loading="loading"
      :loading-options="loadingOption"
      autoresize
    />
  </div>
</template>

<style scoped>
.galaxy-mixed-chart {
  position: relative;
}

/* Dark mode support */
:deep(.dark) .galaxy-mixed-chart {
  color-scheme: dark;
}
</style>

// data/sources/react/mixed-chart/MixedChart.tsx
import React, { useMemo } from 'react'
import ReactECharts from 'echarts-for-react'
import type { EChartsOption } from 'echarts'
import { cn } from '@/lib/utils'
import type { MixedChartProps } from './types'
import { getDefaultColors } from './utils'

export interface MixedChartComponentProps extends MixedChartProps {
  className?: string
}

export const MixedChart = React.forwardRef<ReactECharts, MixedChartComponentProps>(
  (props, ref) => {
    const {
      data,
      height = 300,
      width = '100%',
      theme = 'light',
      legend = true,
      legendPosition = 'top',
      grid = true,
      tooltip = true,
      animation = true,
      loading = false,
      emptyText = 'No data available',
      className,
      options = {},
    } = props

    const chartOption = useMemo<EChartsOption | null>(() => {
      if (!data || !data.datasets || data.datasets.length === 0) {
        return null
      }

      const colors = getDefaultColors()

      // Build series with mixed types
      const series = data.datasets.map((dataset, index) => {
        const chartType = dataset.type || 'line'
        const color = dataset.color || colors[index % colors.length]

        const baseSeries: {
          name: string
          type: string
          data: number[]
          itemStyle: { color: string }
          smooth?: boolean
          showSymbol?: boolean
          symbolSize?: number
          lineStyle?: { width: number }
          barMaxWidth?: number
          areaStyle?: { opacity: number }
        } = {
          name: dataset.label,
          type: chartType === 'area' ? 'line' : chartType,
          data: dataset.data,
          itemStyle: {
            color: color,
          },
        }

        // Add type-specific configurations
        if (chartType === 'line') {
          return {
            ...baseSeries,
            smooth: dataset.smooth !== false,
            showSymbol: true,
            symbolSize: 6,
            lineStyle: {
              width: 2,
            },
          }
        } else if (chartType === 'bar') {
          return {
            ...baseSeries,
            barMaxWidth: 50,
          }
        } else if (chartType === 'area') {
          return {
            ...baseSeries,
            smooth: true,
            showSymbol: true,
            symbolSize: 6,
            areaStyle: {
              opacity: 0.3,
            },
          }
        }

        return baseSeries
      })

      return {
        backgroundColor: 'transparent',
        color: colors,
        tooltip: tooltip
          ? {
              trigger: 'axis',
              axisPointer: {
                type: 'cross',
                crossStyle: {
                  color: theme === 'dark' ? '#9ca3af' : '#6b7280',
                },
              },
              backgroundColor: theme === 'dark' ? '#18181b' : '#ffffff',
              borderColor: theme === 'dark' ? '#27272a' : '#e4e4e7',
              textStyle: {
                color: theme === 'dark' ? '#fafafa' : '#0a0a0a',
              },
            }
          : undefined,
        legend: legend
          ? {
              data: data.datasets.map((d) => d.label),
              [legendPosition]: legendPosition === 'top' || legendPosition === 'bottom' ? 'center' : '5%',
              [legendPosition === 'left' || legendPosition === 'right' ? 'top' : legendPosition]:
                legendPosition === 'left' || legendPosition === 'right' ? 'middle' : '5%',
              orient: legendPosition === 'left' || legendPosition === 'right' ? 'vertical' : 'horizontal',
              textStyle: {
                color: theme === 'dark' ? '#fafafa' : '#0a0a0a',
              },
            }
          : undefined,
        grid: grid
          ? {
              left: '3%',
              right: '4%',
              bottom: '3%',
              top: legend && legendPosition === 'top' ? '15%' : '10%',
              containLabel: true,
            }
          : undefined,
        xAxis: {
          type: 'category',
          data: data.labels,
          boundaryGap: true,
          axisLine: {
            lineStyle: {
              color: theme === 'dark' ? '#4b5563' : '#d1d5db',
            },
          },
          axisLabel: {
            color: theme === 'dark' ? '#9ca3af' : '#6b7280',
          },
        },
        yAxis: {
          type: 'value',
          axisLine: {
            lineStyle: {
              color: theme === 'dark' ? '#4b5563' : '#d1d5db',
            },
          },
          axisLabel: {
            color: theme === 'dark' ? '#9ca3af' : '#6b7280',
          },
          splitLine: {
            lineStyle: {
              color: theme === 'dark' ? '#374151' : '#e5e7eb',
            },
          },
        },
        series,
        animation: animation,
        animationDuration: animation ? 1000 : 0,
        ...options,
      } as EChartsOption
    }, [data, theme, legend, legendPosition, grid, tooltip, animation, options])

    const dimensions = useMemo(() => {
      return {
        height: `${height}px`,
        width: typeof width === 'number' ? `${width}px` : width,
      }
    }, [width, height])

    // Loading state
    if (loading) {
      return (
        <div className={cn('galaxy-mixed-chart w-full', className)}>
          <div
            style={{ height: `${height}px` }}
            className="flex items-center justify-center"
          >
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </div>
      )
    }

    // Empty state
    if (!chartOption) {
      return (
        <div className={cn('galaxy-mixed-chart w-full', className)}>
          <div
            style={{ height: `${height}px` }}
            className="flex items-center justify-center border border-border rounded-md"
          >
            <p className="text-muted-foreground text-sm">{emptyText}</p>
          </div>
        </div>
      )
    }

    return (
      <div className={cn('galaxy-mixed-chart w-full', className)}>
        <ReactECharts
          ref={ref}
          option={chartOption}
          style={dimensions}
          theme={theme}
          showLoading={loading}
          opts={{ renderer: 'canvas' }}
        />
      </div>
    )
  }
)

MixedChart.displayName = 'MixedChart'
