// data/sources/vue/button/Button.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Button component - Displays a button or a component that looks like a button with variants and sizes
-->
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { Primitive, type PrimitiveProps } from 'radix-vue'
import { type ButtonVariants, buttonVariants } from './variants'
import { cn } from '@/lib/utils'

defineOptions({
  name: 'UiButton',
})

/**
 * Button Props
 * @prop variant - Visual style variant (default, destructive, outline, secondary, ghost, link)
 * @prop size - Size variant (default, sm, lg, icon)
 * @prop asChild - Render as child via Radix Primitive
 * @prop as - Element or component to render
 * @prop class - CSS class names for the button
 * @prop type - Native button type (button, submit, reset)
 * @prop disabled - Disables the button
 */
interface ButtonProps extends PrimitiveProps {
  /** Visual style variant. */
  variant?: ButtonVariants['variant']
  /** Size variant. */
  size?: ButtonVariants['size']
  /** CSS class names for the button. */
  class?: HTMLAttributes['class']
  /** Render as child via Radix Primitive. */
  asChild?: boolean
  /** Element or component to render. */
  as?: string
  /** Native button type. */
  type?: 'button' | 'submit' | 'reset'
  /** Disables the button. */
  disabled?: boolean
}

const props = withDefaults(defineProps<ButtonProps>(), {
  as: 'button',
  variant: 'default',
  size: 'default',
  type: 'button',
  disabled: false,
})

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <Primitive
    :class="cn(buttonVariants({ variant, size }), props.class)"
    v-bind="delegatedProps"
  >
    <slot />
  </Primitive>
</template>

// data/sources/react-native/button/Button.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Button component with multiple variants, sizes, and states
 */

import * as React from 'react';
import { Pressable, Text } from 'react-native';
import { type ButtonVariants, buttonVariants, buttonTextVariants } from './variants';
import { cn } from '@/lib/utils';

export interface ButtonProps extends ButtonVariants {
  /** Visual style variant (default, destructive, outline, secondary, ghost, link) */
  variant?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
  /** Size variant (default, sm, lg, icon) */
  size?: 'default' | 'sm' | 'lg' | 'icon';
  /** Press handler */
  onPress?: () => void;
  /** Disables the button */
  disabled?: boolean;
  /** Button content */
  children?: React.ReactNode;
  /** CSS class names for the button */
  className?: string;
  /** CSS class names for the button text */
  textClassName?: string;
}

const Button = React.forwardRef<React.ElementRef<typeof Pressable>, ButtonProps>(
  ({ className, textClassName, variant, size, children, ...props }, ref) => {
    return (
      <Pressable
        ref={ref}
        className={cn(buttonVariants({ variant, size, className }))}
        {...props}
      >
        {typeof children === 'string' ? (
          <Text className={cn(buttonTextVariants({ variant, size, className: textClassName }))}>
            {children}
          </Text>
        ) : (
          children
        )}
      </Pressable>
    );
  }
);

Button.displayName = 'Button';

export { Button };
