// data/sources/react-native/progress/Progress.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Progress bar component for showing completion percentage
 */

import * as React from 'react';
import { View, Animated } from 'react-native';
import { cn } from '@/lib/utils';

export interface ProgressProps {
  /** Current progress value */
  value?: number;
  /** Maximum progress value */
  max?: number;
  /** CSS class names for the progress root */
  className?: string;
  /** CSS class names for the progress indicator */
  indicatorClassName?: string;
}

const Progress = React.forwardRef<View, ProgressProps>(
  ({ value = 0, max = 100, className, indicatorClassName }, ref) => {
    const percentage = Math.min(Math.max((value / max) * 100, 0), 100);
    const animatedWidth = React.useRef(new Animated.Value(0)).current;

    React.useEffect(() => {
      Animated.spring(animatedWidth, {
        toValue: percentage,
        useNativeDriver: false,
        friction: 8,
        tension: 40,
      }).start();
    }, [percentage, animatedWidth]);

    return (
      <View
        ref={ref}
        className={cn('relative h-2 w-full overflow-hidden rounded-full bg-secondary', className)}
      >
        <Animated.View
          className={cn('h-full bg-primary transition-all', indicatorClassName)}
          style={{
            width: animatedWidth.interpolate({
              inputRange: [0, 100],
              outputRange: ['0%', '100%'],
            }),
          }}
        />
      </View>
    );
  }
);

Progress.displayName = 'Progress';

export { Progress };

// data/sources/vue/progress/Progress.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Progress component - Progress bar indicator with percentage value
-->
<script setup lang="ts">
import { computed } from 'vue';
import { ProgressIndicator, ProgressRoot } from 'radix-vue';
import { cn } from '@/lib/utils';

defineOptions({
  name: 'UiProgress',
})

/**
 * Progress Props
 * @prop modelValue - Current progress value (0-max)
 * @prop max - Maximum value
 * @prop class - CSS class names for the progress bar
 */
interface ProgressProps {
  /** Current progress value (0-max). */
  modelValue?: number | null
  /** Maximum value. */
  max?: number
  /** CSS class names for the progress bar. */
  class?: string
}

const props = withDefaults(defineProps<ProgressProps>(), {
  modelValue: 0,
  max: 100,
})

const percentage = computed(() => {
  const value = props.modelValue ?? 0;
  return Math.min(Math.max((value / props.max) * 100, 0), 100);
});
</script>

<template>
  <ProgressRoot
    :model-value="modelValue"
    :max="max"
    :class="cn('relative h-2 w-full overflow-hidden rounded-full bg-secondary', props.class)"
  >
    <ProgressIndicator
      class="h-full w-full flex-1 bg-primary transition-all"
      :style="`transform: translateX(-${100 - percentage}%)`"
    />
  </ProgressRoot>
</template>
