// data/sources/vue/otp-input/OTPInput.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc OTP Input component - One-time password input
-->
<script setup lang="ts">
import { ref, watch } from 'vue';
import { cn } from '@/lib/utils';

defineOptions({
  name: 'UiOTPInput',
});

const props = withDefaults(
  defineProps<{
    length?: number;
    modelValue?: string;
    disabled?: boolean;
    class?: string;
  }>(),
  {
    length: 6,
    disabled: false,
  }
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
  complete: [value: string];
}>();

const inputs = ref<(HTMLInputElement | null)[]>([]);
const digits = ref<string[]>([]);

watch(
  () => props.modelValue,
  (val) => {
    digits.value = (val || '').split('').slice(0, props.length);
  },
  { immediate: true }
);

function setInputRef(index: number) {
  return (el: unknown) => {
    inputs.value[index] = el as HTMLInputElement | null;
  };
}

function handleChange(index: number, inputValue: string) {
  const digit = inputValue.replace(/\D/g, '').slice(-1);
  digits.value[index] = digit;
  const newValue = digits.value.join('');
  emit('update:modelValue', newValue);
  if (newValue.length === props.length) emit('complete', newValue);
  if (digit && index < props.length - 1) inputs.value[index + 1]?.focus();
}

function handleKeydown(index: number, e: KeyboardEvent) {
  if (e.key === 'Backspace' && !digits.value[index] && index > 0) {
    digits.value[index - 1] = '';
    emit('update:modelValue', digits.value.join(''));
    inputs.value[index - 1]?.focus();
  }
}

function handlePaste(e: ClipboardEvent) {
  e.preventDefault();
  const pasted =
    e.clipboardData
      ?.getData('text')
      .replace(/\D/g, '')
      .slice(0, props.length) || '';
  digits.value = pasted.split('');
  emit('update:modelValue', pasted);
  if (pasted.length === props.length) emit('complete', pasted);
  inputs.value[Math.min(pasted.length, props.length - 1)]?.focus();
}
</script>

<template>
  <div
    :class="cn('flex items-center gap-2', props.class)"
    role="group"
    aria-label="One-time password input"
  >
    <input
      v-for="(_, index) in length"
      :key="index"
      :ref="setInputRef(index)"
      type="text"
      inputmode="numeric"
      pattern="[0-9]*"
      maxlength="1"
      :value="digits[index] || ''"
      :disabled="disabled"
      :class="
        cn(
          'h-12 w-12 rounded-md border border-input bg-background text-center text-lg font-semibold',
          'focus:outline-none focus:ring-2 focus:ring-ring focus:border-ring',
          'disabled:cursor-not-allowed disabled:opacity-50'
        )
      "
      :aria-label="'Digit ' + (index + 1)"
      @input="handleChange(index, ($event.target as HTMLInputElement).value)"
      @keydown="handleKeydown(index, $event)"
      @paste="handlePaste"
      @focus="($event.target as HTMLInputElement).select()"
    />
  </div>
</template>

// data/sources/angular/otp-input/otp-input.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc OTP Input component - One-time password input
 */

import { Component, Input, Output, EventEmitter, ElementRef, QueryList, ViewChildren } from '@angular/core';
import { CommonModule } from '@angular/common';
import { cn } from '../../lib/utils';

@Component({
  selector: 'ui-otp-input',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [class]="cn('flex items-center gap-2', class)" role="group" aria-label="One-time password input">
      <input
        *ngFor="let _ of inputArray; let i = index"
        #otpInput
        type="text"
        inputmode="numeric"
        pattern="[0-9]*"
        maxlength="1"
        [value]="digits[i] || ''"
        [disabled]="disabled"
        [class]="inputClasses"
        [attr.aria-label]="'Digit ' + (i + 1)"
        (input)="handleChange(i, $any($event.target).value)"
        (keydown)="handleKeydown(i, $event)"
        (paste)="handlePaste($event)"
        (focus)="$any($event.target).select()"
      />
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OTPInputComponent {
  @Input() length = 6;
  @Input() disabled = false;
  @Input() class?: string;
  @Output() valueChange = new EventEmitter<string>();
  @Output() complete = new EventEmitter<string>();

  @ViewChildren('otpInput') otpInputs!: QueryList<ElementRef<HTMLInputElement>>;

  digits: string[] = [];
  cn = cn;
  private static nextId = 1;

  get inputClasses(): string {
    return cn(
      'h-12 w-12 rounded-md border border-input bg-background text-center text-lg font-semibold',
      'focus:outline-none focus:ring-2 focus:ring-ring focus:border-ring',
      'disabled:cursor-not-allowed disabled:opacity-50',
    );
  }

  handleChange(index: number, inputValue: string): void {
    const digit = inputValue.replace(/\D/g, '').slice(-1);
    while (this.digits.length < this.length) this.digits.push('');
    this.digits[index] = digit;
    const newValue = this.digits.join('');

    this.valueChange.emit(newValue);
    if (newValue.length === this.length) {
      this.complete.emit(newValue);
    }
    if (digit && index < this.length - 1) {
      this.otpInputs.toArray()[index + 1]?.nativeElement.focus();
    }
  }

  handleKeydown(index: number, e: KeyboardEvent): void {
    if (e.key === 'Backspace') {
      if (!this.digits[index] && index > 0) {
        this.digits[index - 1] = '';
        this.valueChange.emit(this.digits.join(''));
        this.otpInputs.toArray()[index - 1]?.nativeElement.focus();
      }
    }
    if (e.key === 'ArrowLeft' && index > 0) {
      this.otpInputs.toArray()[index - 1]?.nativeElement.focus();
    }
    if (e.key === 'ArrowRight' && index < this.length - 1) {
      this.otpInputs.toArray()[index + 1]?.nativeElement.focus();
    }
  }

  handlePaste(e: ClipboardEvent): void {
    e.preventDefault();
    const pasted = e.clipboardData?.getData('text').replace(/\D/g, '').slice(0, this.length) || '';
    this.digits = pasted.split('');
    this.valueChange.emit(pasted);
    if (pasted.length === this.length) this.complete.emit(pasted);
  }

  get otpInputs(): QueryList<ElementRef<HTMLInputElement>> {
    return (this as any)._otpInputs;
  }

  set otpInputs(value: QueryList<ElementRef<HTMLInputElement>>) {
    (this as any)._otpInputs = value;
  }
}
OTPINPUT
echo angular-otp-done
