// data/sources/react/tags-input/TagsInput.tsx
import * as React from 'react'
import { X } from 'lucide-react'
import { cn } from '@/lib/utils'

export interface TagsInputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'> {
  value?: string[]
  onChange?: (tags: string[]) => void
  onTagAdd?: (tag: string) => void
  onTagRemove?: (tag: string) => void
}

const TagsInput = React.forwardRef<HTMLDivElement, TagsInputProps>(
  (
    {
      className,
      value = [],
      onChange,
      onTagAdd,
      onTagRemove,
      placeholder = 'Add tag...',
      ...props
    },
    ref
  ) => {
    const [inputValue, setInputValue] = React.useState('')
    const inputRef = React.useRef<HTMLInputElement>(null)

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter' && inputValue.trim()) {
        e.preventDefault()
        const newTag = inputValue.trim()
        if (!value.includes(newTag)) {
          const newTags = [...value, newTag]
          onChange?.(newTags)
          onTagAdd?.(newTag)
        }
        setInputValue('')
      } else if (e.key === 'Backspace' && !inputValue && value.length > 0) {
        const lastTag = value[value.length - 1]
        const newTags = value.slice(0, -1)
        onChange?.(newTags)
        onTagRemove?.(lastTag)
      }
    }

    const removeTag = (tagToRemove: string) => {
      const newTags = value.filter((tag) => tag !== tagToRemove)
      onChange?.(newTags)
      onTagRemove?.(tagToRemove)
    }

    return (
      <div
        ref={ref}
        className={cn(
          'flex min-h-10 w-full flex-wrap gap-2 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2',
          className
        )}
        onClick={() => inputRef.current?.focus()}
      >
        {value.map((tag) => (
          <span
            key={tag}
            className="inline-flex items-center gap-1 rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground"
          >
            {tag}
            <button
              type="button"
              className="rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
              onClick={() => removeTag(tag)}
            >
              <X className="h-3 w-3" />
              <span className="sr-only">Remove {tag}</span>
            </button>
          </span>
        ))}
        <input
          ref={inputRef}
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder={value.length === 0 ? placeholder : ''}
          className="flex-1 bg-transparent outline-none placeholder:text-muted-foreground"
          {...props}
        />
      </div>
    )
  }
)
TagsInput.displayName = 'TagsInput'

export { TagsInput }

// data/sources/vue/tags-input/TagsInput.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc TagsInput component - Input field for adding/removing tags with keyboard support
-->
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { ref } from 'vue'
import { X } from 'lucide-vue-next'

interface Props {
  class?: string
  modelValue?: string[]
  placeholder?: string
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: () => [],
  placeholder: 'Add tag...',
})

const emit = defineEmits<{
  'update:modelValue': [value: string[]]
  tagAdd: [tag: string]
  tagRemove: [tag: string]
}>()

const inputValue = ref('')
const inputRef = ref<HTMLInputElement>()

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Enter' && inputValue.value.trim()) {
    e.preventDefault()
    const newTag = inputValue.value.trim()
    if (!props.modelValue.includes(newTag)) {
      const newTags = [...props.modelValue, newTag]
      emit('update:modelValue', newTags)
      emit('tagAdd', newTag)
    }
    inputValue.value = ''
  } else if (e.key === 'Backspace' && !inputValue.value && props.modelValue.length > 0) {
    const lastTag = props.modelValue[props.modelValue.length - 1]
    if (lastTag) {
      const newTags = props.modelValue.slice(0, -1)
      emit('update:modelValue', newTags)
      emit('tagRemove', lastTag)
    }
  }
}

const removeTag = (tagToRemove: string) => {
  const newTags = props.modelValue.filter((tag) => tag !== tagToRemove)
  emit('update:modelValue', newTags)
  emit('tagRemove', tagToRemove)
}
</script>

<template>
  <div
    :class="
      cn(
        'flex min-h-10 w-full flex-wrap gap-2 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2',
        props.class
      )
    "
    @click="inputRef?.focus()"
  >
    <span
      v-for="tag in modelValue"
      :key="tag"
      class="inline-flex items-center gap-1 rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground"
    >
      {{ tag }}
      <button
        type="button"
        class="rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        @click="removeTag(tag)"
      >
        <X class="h-3 w-3" />
        <span class="sr-only">Remove {{ tag }}</span>
      </button>
    </span>
    <input
      ref="inputRef"
      v-model="inputValue"
      type="text"
      :placeholder="modelValue.length === 0 ? placeholder : ''"
      class="flex-1 bg-transparent outline-none placeholder:text-muted-foreground"
      @keydown="handleKeyDown"
    />
  </div>
</template>
