// data/sources/react-native/tags-input/TagsInput.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Tags Input - enter tags with chips + remove
 */

import * as React from 'react';
import { View, Text, TextInput, Pressable } from 'react-native';
import { cn } from '@/lib/utils';

export interface TagsInputProps {
  value?: string[];
  onChange?: (tags: string[]) => void;
  placeholder?: string;
  disabled?: boolean;
  className?: string;
}

export function TagsInput({ value = [], onChange, placeholder = 'Add tag...', disabled, className }: TagsInputProps) {
  const [input, setInput] = React.useState('');

  const addTag = () => {
    const tag = input.trim();
    if (!tag || value.includes(tag)) { setInput(''); return; }
    onChange?.([...value, tag]);
    setInput('');
  };

  const removeTag = (tag: string) => onChange?.(value.filter((t) => t !== tag));

  return (
    <View className={cn('flex-row flex-wrap items-center gap-2 rounded-md border border-input bg-background p-2', className)}>
      {value.map((tag) => (
        <View key={tag} className="flex-row items-center gap-1 rounded-md bg-secondary px-2 py-1">
          <Text className="text-sm">{tag}</Text>
          {!disabled && (
            <Pressable onPress={() => removeTag(tag)} hitSlop={8}>
              <Text className="text-muted-foreground">×</Text>
            </Pressable>
          )}
        </View>
      ))}
      <TextInput
        value={input}
        onChangeText={setInput}
        onSubmitEditing={() => { onChange?.([...value, input.trim()]); setInput(''); }}
        onBlur={() => { if (input.trim()) { onChange?.([...value, input.trim()]); setInput(''); } }}
        placeholder={placeholder}
        editable={!disabled}
        className="min-w-[100px] flex-1 text-sm"
      />
    </View>
  );
}

// data/sources/vue/tags-input/TagsInput.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc TagsInput component - Input field for adding/removing tags with keyboard support
-->
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { ref } from 'vue'
import { X } from 'lucide-vue-next'

interface Props {
  class?: string
  modelValue?: string[]
  placeholder?: string
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: () => [],
  placeholder: 'Add tag...',
})

const emit = defineEmits<{
  'update:modelValue': [value: string[]]
  tagAdd: [tag: string]
  tagRemove: [tag: string]
}>()

const inputValue = ref('')
const inputRef = ref<HTMLInputElement>()

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Enter' && inputValue.value.trim()) {
    e.preventDefault()
    const newTag = inputValue.value.trim()
    if (!props.modelValue.includes(newTag)) {
      const newTags = [...props.modelValue, newTag]
      emit('update:modelValue', newTags)
      emit('tagAdd', newTag)
    }
    inputValue.value = ''
  } else if (e.key === 'Backspace' && !inputValue.value && props.modelValue.length > 0) {
    const lastTag = props.modelValue[props.modelValue.length - 1]
    if (lastTag) {
      const newTags = props.modelValue.slice(0, -1)
      emit('update:modelValue', newTags)
      emit('tagRemove', lastTag)
    }
  }
}

const removeTag = (tagToRemove: string) => {
  const newTags = props.modelValue.filter((tag) => tag !== tagToRemove)
  emit('update:modelValue', newTags)
  emit('tagRemove', tagToRemove)
}
</script>

<template>
  <div
    :class="
      cn(
        'flex min-h-10 w-full flex-wrap gap-2 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2',
        props.class
      )
    "
    @click="inputRef?.focus()"
  >
    <span
      v-for="tag in modelValue"
      :key="tag"
      class="inline-flex items-center gap-1 rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground"
    >
      {{ tag }}
      <button
        type="button"
        class="rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        @click="removeTag(tag)"
      >
        <X class="h-3 w-3" />
        <span class="sr-only">Remove {{ tag }}</span>
      </button>
    </span>
    <input
      ref="inputRef"
      v-model="inputValue"
      type="text"
      :placeholder="modelValue.length === 0 ? placeholder : ''"
      class="flex-1 bg-transparent outline-none placeholder:text-muted-foreground"
      @keydown="handleKeyDown"
    />
  </div>
</template>
