// data/sources/vue/label/Label.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Label component - Renders an accessible label associated with controls
-->
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { Label as RadixLabel, type LabelProps as RadixLabelProps } from 'radix-vue'
import { cn } from '@/lib/utils'

defineOptions({
  name: 'UiLabel',
})

/**
 * Label Props
 * @prop for - Id of the element the label is associated with
 * @prop asChild - Render as child via Radix Primitive
 * @prop as - Element or component to render
 * @prop class - CSS class names for the label
 */
interface LabelProps extends RadixLabelProps {
  /** Id of the element the label is associated with. */
  htmlFor?: string
  /** Render as child via Radix Primitive. */
  asChild?: boolean
  /** Element or component to render. */
  as?: string
  /** CSS class names for the label. */
  class?: HTMLAttributes['class']
}

const props = defineProps<LabelProps>()

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <RadixLabel
    :class="cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      props.class
    )"
    v-bind="delegatedProps"
  >
    <slot />
  </RadixLabel>
</template>

// data/sources/react/label/Label.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Label component - Renders an accessible label associated with controls
 */

import * as React from 'react'
import * as LabelPrimitive from '@radix-ui/react-label'
import { cn } from '@/lib/utils'

/**
 * Label Component
 * 
 * Renders an accessible label associated with controls.
 * Built on top of Radix UI Label primitive.
 * 
 * @param {React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>} props - Label props
 * @param {string} [props.className] - CSS class names for the label
 * @param {string} [props.htmlFor] - ID of the associated control
 * @param {React.ReactNode} [props.children] - Label content
 * @param {React.RefObject<React.ElementRef<typeof LabelPrimitive.Root>>} ref - Reference to the label element
 * @returns {JSX.Element} Label element
 */
const Label = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>
>(({ className, ...props }, ref) => (
  <LabelPrimitive.Root
    ref={ref}
    className={cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      className
    )}
    {...props}
  />
))
Label.displayName = LabelPrimitive.Root.displayName

export { Label }
