// data/sources/angular/skeleton/skeleton.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Placeholder component for loading states
 */

import { Component, Input } from '@angular/core'
import { cn } from '../../lib/utils'

@Component({
  selector: 'ui-skeleton',
  standalone: true,
  template: `
    <div [class]="className">
      <ng-content />
    </div>
  `,
})
export class SkeletonComponent {
  /**
   * CSS class
   */
  @Input() class?: string

  /**
   * Skeleton variant
   * @default "default"
   */
  @Input() variant: 'default' | 'circle' | 'text' = 'default'

  get className(): string {
    return cn(
      'animate-pulse bg-muted',
      {
        'rounded-md': this.variant === 'default',
        'rounded-full': this.variant === 'circle',
        'h-4 rounded': this.variant === 'text',
      },
      this.class
    )
  }
}

// data/sources/react/skeleton/Skeleton.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Skeleton component - Display a placeholder while content is loading
 */

import * as React from 'react'
import { cn } from '@/lib/utils'

export interface SkeletonProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Skeleton variant
   * @default "default"
   */
  variant?: 'default' | 'circle' | 'text'
}

const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(
  ({ className, variant = 'default', ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn(
          'animate-pulse bg-muted',
          {
            'rounded-md': variant === 'default',
            'rounded-full': variant === 'circle',
            'h-4 rounded': variant === 'text',
          },
          className
        )}
        {...props}
      />
    )
  }
)
Skeleton.displayName = 'Skeleton'

export { Skeleton }
