// data/sources/react-native/tooltip/Tooltip.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Tooltip component for contextual information on hover or focus
 */

import * as React from 'react';
import * as TooltipPrimitive from '@rn-primitives/tooltip';
import { cn } from '@/lib/utils';

/**
 * Tooltip provider component - must wrap all tooltip components
 */
const TooltipProvider = TooltipPrimitive.Provider;

/**
 * Tooltip root component
 * @property open - Controlled open state
 * @property defaultOpen - Uncontrolled initial open state
 * @property onOpenChange - Called when the open state changes
 * @property delayDuration - Time to wait before showing tooltip
 * @property skipDelayDuration - Time to skip delay for rapid hovers
 */
const Tooltip = TooltipPrimitive.Root;

/**
 * Tooltip trigger component - wraps the element that triggers the tooltip
 */
const TooltipTrigger = TooltipPrimitive.Trigger;

const TooltipContent = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <TooltipPrimitive.Content
    ref={ref}
    sideOffset={sideOffset}
    className={cn(
      'z-50 overflow-hidden rounded-md border border-border bg-popover px-3 py-1.5 text-sm text-popover-foreground shadow-md',
      'animate-in fade-in-0 zoom-in-95',
      'data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95',
      'data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2',
      className
    )}
    {...props}
  />
));
TooltipContent.displayName = TooltipPrimitive.Content.displayName;

export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider };

// data/sources/angular/tooltip/tooltip.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Tooltip popup triggered by hover or focus
 */

import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  RdxTooltipRootDirective,
  RdxTooltipTriggerDirective,
  RdxTooltipContentDirective,
} from '@radix-ng/primitives/tooltip';
import { cn } from '../../lib/utils';

@Component({
  selector: 'ui-tooltip',
  standalone: true,
  imports: [CommonModule, RdxTooltipRootDirective],
  template: `
    <span rdxTooltipRoot>
      <ng-content></ng-content>
    </span>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TooltipComponent {}

@Component({
  selector: 'ui-tooltip-trigger',
  standalone: true,
  imports: [CommonModule, RdxTooltipTriggerDirective],
  template: `
    <button rdxTooltipTrigger [class]="triggerClasses">
      <ng-content></ng-content>
    </button>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TooltipTriggerComponent {
  @Input() class?: string;

  get triggerClasses(): string {
    return cn('', this.class);
  }
}

@Component({
  selector: 'ui-tooltip-content',
  standalone: true,
  imports: [CommonModule, RdxTooltipContentDirective],
  template: `
    <div rdxTooltipContent [class]="contentClasses">
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TooltipContentComponent {
  @Input() class?: string;

  get contentClasses(): string {
    return cn(
      'z-50 overflow-hidden rounded-md border bg-popover px-3 py-1.5 text-sm text-popover-foreground shadow-md animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2',
      this.class
    );
  }
}
