// data/sources/vue/kbd/Kbd.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Kbd component - Keyboard key display with 3 size variants (sm, default, lg)
-->
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { computed } from 'vue'

defineOptions({
  name: 'UiKbd',
})

interface Props {
  /**
   * CSS class
   */
  class?: string
  /**
   * Size variant
   * @default "default"
   */
  size?: 'sm' | 'default' | 'lg'
}

const props = withDefaults(defineProps<Props>(), {
  size: 'default',
})

const className = computed(() =>
  cn(
    'inline-flex items-center justify-center rounded border border-border bg-muted px-2 font-mono text-sm font-medium text-muted-foreground shadow-sm',
    {
      'h-5 min-w-[20px] text-xs': props.size === 'sm',
      'h-6 min-w-[24px] text-sm': props.size === 'default',
      'h-7 min-w-[28px] text-base': props.size === 'lg',
    },
    props.class
  )
)
</script>

<template>
  <kbd :class="className">
    <slot />
  </kbd>
</template>

// data/sources/react/kbd/Kbd.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Kbd component - Displays keyboard keys with styled formatting
 */

import * as React from 'react'
import { cn } from '@/lib/utils'

export interface KbdProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Size variant
   * @default "default"
   */
  size?: 'sm' | 'default' | 'lg'
}

const Kbd = React.forwardRef<HTMLElement, KbdProps>(
  ({ className, size = 'default', ...props }, ref) => {
    return (
      <kbd
        ref={ref}
        className={cn(
          'inline-flex items-center justify-center rounded border border-border bg-muted px-2 font-mono text-sm font-medium text-muted-foreground shadow-sm',
          {
            'h-5 min-w-[20px] text-xs': size === 'sm',
            'h-6 min-w-[24px] text-sm': size === 'default',
            'h-7 min-w-[28px] text-base': size === 'lg',
          },
          className
        )}
        {...props}
      />
    )
  }
)
Kbd.displayName = 'Kbd'

export { Kbd }
