// data/sources/angular/aspect-ratio/aspect-ratio.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Container for maintaining aspect ratio of embedded content
 */

import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RdxAspectRatioDirective } from '@radix-ng/primitives/aspect-ratio';

@Component({
  selector: 'ui-aspect-ratio',
  standalone: true,
  imports: [CommonModule, RdxAspectRatioDirective],
  template: `
    <div rdxAspectRatio [ratio]="ratio" [class]="aspectRatioClasses">
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AspectRatioComponent {
  @Input() ratio: number = 16 / 9;
  @Input() class?: string;

  get aspectRatioClasses(): string {
    return this.class || '';
  }
}

// data/sources/vue/aspect-ratio/AspectRatio.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc AspectRatio component - Maintains aspect ratio for embedded content
-->
<script setup lang="ts">
import { AspectRatio as AspectRatioPrimitive, type AspectRatioProps } from 'radix-vue'

interface Props extends AspectRatioProps {}

defineProps<Props>()
</script>

<template>
  <AspectRatioPrimitive v-bind="$props">
    <slot />
  </AspectRatioPrimitive>
</template>
