// data/sources/angular/line-chart/line-chart.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Line Chart component - Responsive line chart powered by ECharts
 */

import {
  Component,
  Input,
  OnInit,
  OnChanges,
  SimpleChanges,
  ChangeDetectionStrategy,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import { NgxEchartsModule } from 'ngx-echarts'
import type { EChartsOption } from 'echarts'
import { cn } from '../../lib/utils'
import type { ChartData } from './types'
import {
  buildEChartsOption,
  getResponsiveDimensions,
  transformDataToSeries,
} from './utils'

@Component({
  selector: 'ui-line-chart',
  standalone: true,
  imports: [CommonModule, NgxEchartsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="containerClass">
      <!-- Empty State -->
      <div
        *ngIf="!chartOption && !loading"
        class="flex items-center justify-center bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700"
        [style.height]="dimensions.height"
      >
        <p class="text-gray-500 dark:text-gray-400">{{ emptyText }}</p>
      </div>

      <!-- Chart -->
      <div
        *ngIf="chartOption"
        echarts
        [options]="chartOption"
        [theme]="theme"
        [loading]="loading"
        [loadingOpts]="loadingOption"
        [style.height]="dimensions.height"
        [style.width]="dimensions.width"
        class="echarts-container"
      ></div>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
      }

      .echarts-container {
        position: relative;
      }

      /* Dark mode support */
      :host-context(.dark) {
        color-scheme: dark;
      }
    `,
  ],
})
export class LineChartComponent implements OnInit, OnChanges {
  @Input({ required: true }) data!: ChartData
  @Input() height: number = 300
  @Input() width?: number | string
  @Input() theme: 'light' | 'dark' = 'light'
  @Input() legend: boolean = true
  @Input() legendPosition: 'top' | 'bottom' | 'left' | 'right' = 'top'
  @Input() grid: boolean | GridConfig = true
  @Input() tooltip: boolean | TooltipConfig = true
  @Input() animation: boolean = true
  @Input() smooth: boolean = true
  @Input() showPoints: boolean = true
  @Input() pointSize: number = 6
  @Input() area: boolean = false
  @Input() stack: boolean = false
  @Input() zoom: boolean = false
  @Input() dataLabels: boolean = false
  @Input() loading: boolean = false
  @Input() emptyText: string = 'No data available'
  @Input() className?: string
  @Input() options: Record<string, unknown> = {}

  chartOption: EChartsOption | null = null
  dimensions: { width: string; height: string } = { width: '100%', height: '300px' }

  loadingOption = {
    text: 'Loading...',
    color: '#3b82f6',
    textColor: '#666',
    maskColor: 'rgba(255, 255, 255, 0.8)',
    zlevel: 0,
  }

  get containerClass(): string {
    return cn('galaxy-line-chart w-full', this.className)
  }

  ngOnInit(): void {
    this.updateChart()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (
      changes['data'] ||
      changes['height'] ||
      changes['width'] ||
      changes['theme'] ||
      changes['smooth'] ||
      changes['area'] ||
      changes['options']
    ) {
      this.updateChart()
    }
  }

  private updateChart(): void {
    // Update dimensions
    this.dimensions = getResponsiveDimensions(this.width, this.height)

    // Check for empty data
    if (!this.data || !this.data.datasets || this.data.datasets.length === 0) {
      this.chartOption = null
      return
    }

    // Build base option
    const baseOption = buildEChartsOption({
      data: this.data,
      height: this.height,
      width: this.width,
      theme: this.theme,
      legend: this.legend,
      legendPosition: this.legendPosition,
      grid: this.grid,
      tooltip: this.tooltip,
      animation: this.animation,
      zoom: this.zoom,
      options: this.options,
      chartType: 'line',
    })

    // Apply line-specific configurations
    const series = transformDataToSeries(this.data, 'line', {
      smooth: this.smooth,
      showSymbol: this.showPoints,
      symbolSize: this.pointSize,
      stack: this.stack ? 'total' : undefined,
      areaStyle: this.area
        ? {
            opacity: 0.3,
          }
        : undefined,
      label: this.dataLabels
        ? {
            show: true,
            position: 'top',
          }
        : undefined,
    })

    this.chartOption = {
      ...baseOption,
      series,
    }
  }
}

// data/sources/react/line-chart/LineChart.tsx
/**
 * Galaxy UI Charts - React LineChart Component
 *
 * A responsive line chart component powered by ECharts
 */

import React, { useMemo } from 'react'
import ReactECharts from 'echarts-for-react'
import type { EChartsOption } from 'echarts'
import { cn } from '@/lib/utils'
import type { LineChartProps } from './types'
import {
  buildEChartsOption,
  getResponsiveDimensions,
  transformDataToSeries,
} from './utils'

export interface LineChartComponentProps extends LineChartProps {
  className?: string
}

export const LineChart = React.forwardRef<ReactECharts, LineChartComponentProps>(
  (props, ref) => {
    const {
      data,
      height = 300,
      width,
      theme = 'light',
      legend = true,
      legendPosition = 'top',
      grid = true,
      tooltip = true,
      smooth = true,
      showPoints = true,
      pointSize = 6,
      area = false,
      stack = false,
      zoom = false,
      dataLabels = false,
      animation = true,
      loading = false,
      emptyText = 'No data available',
      className,
      options = {},
    } = props

    // Build ECharts option
    const chartOption = useMemo<EChartsOption | null>(() => {
      // Check for empty data
      if (!data || !data.datasets || data.datasets.length === 0) {
        return null
      }

      const baseOption = buildEChartsOption({
        data,
        height,
        width,
        theme,
        legend,
        legendPosition,
        grid,
        tooltip,
        animation,
        zoom,
        options,
        chartType: 'line',
      })

      // Apply line-specific configurations
      const series = transformDataToSeries(data, 'line', {
        smooth,
        showSymbol: showPoints,
        symbolSize: pointSize,
        stack: stack ? 'total' : undefined,
        areaStyle: area
          ? {
              opacity: 0.3,
            }
          : undefined,
        label: dataLabels
          ? {
              show: true,
              position: 'top',
            }
          : undefined,
      })

      return {
        ...baseOption,
        series,
      }
    }, [
      data,
      height,
      width,
      theme,
      legend,
      legendPosition,
      grid,
      tooltip,
      animation,
      smooth,
      showPoints,
      pointSize,
      area,
      stack,
      zoom,
      dataLabels,
      options,
    ])

    // Get responsive dimensions
    const dimensions = useMemo(
      () => getResponsiveDimensions(width, height),
      [width, height]
    )

    // Loading option
    const loadingOption = useMemo(
      () => ({
        text: 'Loading...',
        color: '#3b82f6',
        textColor: '#666',
        maskColor: 'rgba(255, 255, 255, 0.8)',
        zlevel: 0,
      }),
      []
    )

    // Empty state
    if (!chartOption && !loading) {
      return (
        <div className={cn('galaxy-line-chart w-full', className)}>
          <div
            className="flex items-center justify-center bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700"
            style={{ height: dimensions.height }}
          >
            <p className="text-gray-500 dark:text-gray-400">{emptyText}</p>
          </div>
        </div>
      )
    }

    // Render chart
    return (
      <div className={cn('galaxy-line-chart w-full', className)}>
        {chartOption && (
          <ReactECharts
            ref={ref}
            option={chartOption}
            style={dimensions}
            theme={theme}
            showLoading={loading}
            loadingOption={loadingOption}
            opts={{ renderer: 'canvas' }}
            notMerge
            lazyUpdate
          />
        )}
      </div>
    )
  }
)

LineChart.displayName = 'LineChart'

export default LineChart
