// data/sources/vue/tooltip/Tooltip.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Tooltip component - Popover that displays information on hover or focus
-->
<script setup lang="ts">
import { TooltipRoot, type TooltipRootProps } from 'radix-vue'

defineOptions({
  name: 'UiTooltip',
})

/**
 * Tooltip Props
 * @prop open - Controlled open state
 * @prop defaultOpen - Default open state
 * @prop delayDuration - Delay before showing tooltip
 * @prop disableHoverableContent - Disables hoverable content
 * @prop side - Side to display (top, right, bottom, left)
 * @prop align - Alignment (start, center, end)
 */
interface Props extends TooltipRootProps {
  /** Controlled open state. */
  open?: boolean
  /** Default open state. */
  defaultOpen?: boolean
  /** Delay before showing tooltip. */
  delayDuration?: number
  /** Disables hoverable content. */
  disableHoverableContent?: boolean
  /** Side to display (top, right, bottom, left). */
  side?: 'top' | 'right' | 'bottom' | 'left'
  /** Alignment (start, center, end). */
  align?: 'start' | 'center' | 'end'
}
defineProps<Props>()
</script>

<template>
  <TooltipRoot v-bind="$props"><slot /></TooltipRoot>
</template>

// data/sources/react-native/tooltip/Tooltip.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Tooltip component for contextual information on hover or focus
 */

import * as React from 'react';
import * as TooltipPrimitive from '@rn-primitives/tooltip';
import { cn } from '@/lib/utils';

/**
 * Tooltip provider component - must wrap all tooltip components
 */
const TooltipProvider = TooltipPrimitive.Provider;

/**
 * Tooltip root component
 * @property open - Controlled open state
 * @property defaultOpen - Uncontrolled initial open state
 * @property onOpenChange - Called when the open state changes
 * @property delayDuration - Time to wait before showing tooltip
 * @property skipDelayDuration - Time to skip delay for rapid hovers
 */
const Tooltip = TooltipPrimitive.Root;

/**
 * Tooltip trigger component - wraps the element that triggers the tooltip
 */
const TooltipTrigger = TooltipPrimitive.Trigger;

const TooltipContent = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <TooltipPrimitive.Content
    ref={ref}
    sideOffset={sideOffset}
    className={cn(
      'z-50 overflow-hidden rounded-md border border-border bg-popover px-3 py-1.5 text-sm text-popover-foreground shadow-md',
      'animate-in fade-in-0 zoom-in-95',
      'data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95',
      'data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2',
      className
    )}
    {...props}
  />
));
TooltipContent.displayName = TooltipPrimitive.Content.displayName;

export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider };
