// data/sources/react/scroll-area/ScrollArea.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc ScrollArea component - A scrollable area with custom scrollbars
 */

import * as React from 'react'
import * as ScrollAreaPrimitive from '@radix-ui/react-scroll-area'
import { cn } from '@/lib/utils'

/**
 * ScrollArea Component
 * 
 * A scrollable area with custom scrollbars that supports both vertical and horizontal scrolling.
 * Built on top of Radix UI ScrollArea primitive.
 * 
 * @param {React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root>} props - ScrollArea props
 * @param {string} [props.className] - CSS class names for the scroll area
 * @param {React.ReactNode} [props.children] - Scrollable content
 * @param {string} [props.type] - Scrollbar visibility type (auto, always, scroll, hover)
 * @param {string} [props.direction] - Scroll direction (ltr, rtl)
 * @param {React.RefObject<React.ElementRef<typeof ScrollAreaPrimitive.Root>>} ref - Reference to the scroll area element
 * @returns {JSX.Element} Scroll area element
 */

const ScrollArea = React.forwardRef<
  React.ElementRef<typeof ScrollAreaPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root>
>(({ className, children, ...props }, ref) => (
  <ScrollAreaPrimitive.Root
    ref={ref}
    className={cn('relative overflow-hidden', className)}
    {...props}
  >
    <ScrollAreaPrimitive.Viewport className="h-full w-full rounded-[inherit]">
      {children}
    </ScrollAreaPrimitive.Viewport>
    <ScrollBar />
    <ScrollAreaPrimitive.Corner />
  </ScrollAreaPrimitive.Root>
))
ScrollArea.displayName = ScrollAreaPrimitive.Root.displayName

const ScrollBar = React.forwardRef<
  React.ElementRef<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>,
  React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>
>(({ className, orientation = 'vertical', ...props }, ref) => (
  <ScrollAreaPrimitive.ScrollAreaScrollbar
    ref={ref}
    orientation={orientation}
    className={cn(
      'flex touch-none select-none transition-colors',
      orientation === 'vertical' &&
        'h-full w-2.5 border-l border-l-transparent p-[1px]',
      orientation === 'horizontal' &&
        'h-2.5 flex-col border-t border-t-transparent p-[1px]',
      className
    )}
    {...props}
  >
    <ScrollAreaPrimitive.ScrollAreaThumb className="relative flex-1 rounded-full bg-border" />
  </ScrollAreaPrimitive.ScrollAreaScrollbar>
))
ScrollBar.displayName = ScrollAreaPrimitive.ScrollAreaScrollbar.displayName

export { ScrollArea, ScrollBar }

// data/sources/vue/scroll-area/ScrollArea.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc ScrollArea component - Custom styled scroll container with scrollbars
-->
<script setup lang="ts">
import { ScrollAreaRoot, ScrollAreaViewport, ScrollAreaCorner, type ScrollAreaRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'
import ScrollBar from './ScrollBar.vue'

/**
 * ScrollArea Props
 * @prop type - Scrollbar type (auto, always, hover, scroll)
 * @prop dir - Text direction (ltr, rtl)
 * @prop class - CSS class names for the scroll area
 */
interface Props extends ScrollAreaRootProps {
  /** Scrollbar type (auto, always, hover, scroll). */
  type?: 'auto' | 'always' | 'hover' | 'scroll'
  /** Text direction (ltr, rtl). */
  dir?: 'ltr' | 'rtl'
  /** CSS class names for the scroll area. */
  class?: string
}

const props = defineProps<Props>()
</script>

<template>
  <ScrollAreaRoot :class="cn('relative overflow-hidden', props.class)" v-bind="props">
    <ScrollAreaViewport class="h-full w-full rounded-[inherit]">
      <slot />
    </ScrollAreaViewport>
    <ScrollBar />
    <ScrollAreaCorner />
  </ScrollAreaRoot>
</template>
